// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6306, generator: {generator})
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Runtime
{
    public class OdataError
    {

        /// <summary>Backing field for <see cref="Error" /> property.</summary>
        private OdataErrorMain _error;

        [Info(
        Required = true,
        ReadOnly = false,
        Description = @"",
        SerializedName = @"error",
        PossibleTypes = new [] { typeof(OdataErrorMain) })]
        [Origin(PropertyOrigin.Owned)]
        public OdataErrorMain Error { get => _error = _error ?? new OdataErrorMain(); set => _error = value; }
    }
}