// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6306, generator: {generator})
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using Microsoft.Graph.PowerShell.Runtime;

namespace Microsoft.Graph.PowerShell.Security.Models
{
    /// <summary>keyValuePair</summary>
    public class MicrosoftGraphKeyValuePair
    {
        /// <summary>
        ///     Name for this key-value pair. Possible names are: AdditionalWSFedEndpointCheckResult,
        ///     AllowedAuthenticationClassReferencesCheckResult,
        ///     AlwaysRequireAuthenticationCheckResult, AutoUpdateEnabledCheckResult, ClaimsProviderNameCheckResult,
        ///     EncryptClaimsCheckResult,
        ///     EncryptedNameIdRequiredCheckResult, MonitoringEnabledCheckResult,NotBeforeSkewCheckResult,
        ///     RequestMFAFromClaimsProvidersCheckResult,
        ///     SignedSamlRequestsRequiredCheckResult, AdditionalAuthenticationRulesCheckResult, TokenLifetimeCheckResult,
        ///     DelegationAuthorizationRulesCheckResult,
        ///     IssuanceAuthorizationRulesCheckResult, IssuanceTransformRulesCheckResult.
        /// </summary>
        [Info(
            Required = false,
            ReadOnly = false,
            Description =
                @"Name for this key-value pair. Possible names are: AdditionalWSFedEndpointCheckResult,  AllowedAuthenticationClassReferencesCheckResult, AlwaysRequireAuthenticationCheckResult,   AutoUpdateEnabledCheckResult, ClaimsProviderNameCheckResult, EncryptClaimsCheckResult,  EncryptedNameIdRequiredCheckResult, MonitoringEnabledCheckResult,NotBeforeSkewCheckResult,  RequestMFAFromClaimsProvidersCheckResult, SignedSamlRequestsRequiredCheckResult, AdditionalAuthenticationRulesCheckResult, TokenLifetimeCheckResult,  DelegationAuthorizationRulesCheckResult, IssuanceAuthorizationRulesCheckResult, IssuanceTransformRulesCheckResult.",
            SerializedName = @"name",
            PossibleTypes = new[] {typeof(string)})]
        [Origin(PropertyOrigin.Owned)]
        public string Name { get; set; }

        /// <summary>
        ///     Value for this key-value pair. Possible result values are 0 (when the validation check passed), 1 (when the
        ///     validation
        ///     check failed), or 2 (when the validation check is a warning).
        /// </summary>
        [Info(
            Required = false,
            ReadOnly = false,
            Description =
                @"Value for this key-value pair. Possible result values are 0 (when the validation check passed), 1 (when the validation check failed), or 2 (when the validation check is a warning).",
            SerializedName = @"value",
            PossibleTypes = new[] {typeof(string)})]
        [Origin(PropertyOrigin.Owned)]
        public string Value { get; set; }
    }
}