// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6306, generator: {generator})
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace Microsoft.Graph.PowerShell.Security.Models
{
    /// <summary>secureScoreControlStateUpdate</summary>
    public class MicrosoftGraphSecureScoreControlStateUpdate
    {
        [Origin(PropertyOrigin.Owned)] public string AssignedTo { get; set; }

        [Origin(PropertyOrigin.Owned)] public string Comment { get; set; }

        [Origin(PropertyOrigin.Owned)] public string State { get; set; }

        [Origin(PropertyOrigin.Owned)] public string UpdatedBy { get; set; }

        [Origin(PropertyOrigin.Owned)] public DateTime? UpdatedDateTime { get; set; }
    }
}