// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6306, generator: {generator})
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace Microsoft.Graph.PowerShell.Security.Models
{
    /// <summary>secureScore</summary>
    public class MicrosoftGraphSecureScore
    {
        private readonly MicrosoftGraphEntity __microsoftGraphEntity = new MicrosoftGraphEntity();

        /// <summary>Backing field for <see cref="ActiveUserCount" /> property.</summary>
        private int? _activeUserCount;

        private MicrosoftGraphSecurityVendorInformation _vendorInformation;

        /// <summary>Active user count of the given tenant.</summary>
        [Origin(PropertyOrigin.Owned)]
        public int? ActiveUserCount
        {
            get => _activeUserCount;
            set => _activeUserCount = value;
        }

        /// <summary>
        ///     Average score by different scopes (for example, average by industry, average by seating) and control category
        ///     (Identity,
        ///     Data, Device, Apps, Infrastructure) within the scope.
        /// </summary>
        [Origin(PropertyOrigin.Owned)]
        public MicrosoftGraphAverageComparativeScore[] AverageComparativeScores { get; set; }

        /// <summary>GUID string for tenant ID.</summary>
        [Origin(PropertyOrigin.Owned)]
        public string AzureTenantId { get; set; }

        /// <summary>Contains tenant scores for a set of controls.</summary>
        [Origin(PropertyOrigin.Owned)]
        public MicrosoftGraphControlScore[] ControlScores { get; set; }

        /// <summary>The date when the entity is created.</summary>
        [Origin(PropertyOrigin.Owned)]
        public DateTime? CreatedDateTime { get; set; }

        /// <summary>Tenant current attained score on specified date.</summary>
        [Origin(PropertyOrigin.Owned)]
        public double? CurrentScore { get; set; }

        /// <summary>
        ///     Microsoft-provided services for the tenant (for example, Exchange online, Skype, Sharepoint).
        /// </summary>
        [Origin(PropertyOrigin.Owned)]
        public string[] EnabledServices { get; set; }

        /// <summary>Read-only.</summary>
        [Origin(PropertyOrigin.Inherited)]
        public string Id
        {
            get => __microsoftGraphEntity.Id;
            set => __microsoftGraphEntity.Id = value;
        }

        /// <summary>Licensed user count of the given tenant.</summary>
        [Origin(PropertyOrigin.Owned)]
        public int? LicensedUserCount { get; set; }

        /// <summary>Tenant maximum possible score on specified date.</summary>
        [Origin(PropertyOrigin.Owned)]
        public double? MaxScore { get; set; }

        /// <summary>securityVendorInformation</summary>
        [Origin(PropertyOrigin.Owned)]
        public MicrosoftGraphSecurityVendorInformation VendorInformation
        {
            get => _vendorInformation = _vendorInformation ?? new MicrosoftGraphSecurityVendorInformation();
            set => _vendorInformation = value;
        }
    }
}