// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6306, generator: {generator})
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using Microsoft.Graph.PowerShell.Runtime;

namespace Microsoft.Graph.PowerShell.Security.Models
{
    /// <summary>hostSecurityState</summary>
    public class MicrosoftGraphHostSecurityState
    {
        /// <summary>Host FQDN (Fully Qualified Domain Name) (for example, machine.company.com).</summary>
        [Info(
            Required = false,
            ReadOnly = false,
            Description = @"Host FQDN (Fully Qualified Domain Name) (for example, machine.company.com).",
            SerializedName = @"fqdn",
            PossibleTypes = new[] {typeof(string)})]
        [Origin(PropertyOrigin.Owned)]
        public string Fqdn { get; set; }

        [Info(
            Required = false,
            ReadOnly = false,
            Description = @"",
            SerializedName = @"isAzureAdJoined",
            PossibleTypes = new[] {typeof(bool)})]
        [Origin(PropertyOrigin.Owned)]
        public bool? IsAzureAdJoined { get; set; }

        [Info(
            Required = false,
            ReadOnly = false,
            Description = @"",
            SerializedName = @"isAzureAdRegistered",
            PossibleTypes = new[] {typeof(bool)})]
        [Origin(PropertyOrigin.Owned)]
        public bool? IsAzureAdRegistered { get; set; }

        /// <summary>True if the host is domain joined to an on-premises Active Directory domain.</summary>
        [Info(
            Required = false,
            ReadOnly = false,
            Description = @"True if the host is domain joined to an on-premises Active Directory domain.",
            SerializedName = @"isHybridAzureDomainJoined",
            PossibleTypes = new[] {typeof(bool)})]
        [Origin(PropertyOrigin.Owned)]
        public bool? IsHybridAzureDomainJoined { get; set; }

        /// <summary>The local host name, without the DNS domain name.</summary>
        [Info(
            Required = false,
            ReadOnly = false,
            Description = @"The local host name, without the DNS domain name.",
            SerializedName = @"netBiosName",
            PossibleTypes = new[] {typeof(string)})]
        [Origin(PropertyOrigin.Owned)]
        public string NetBiosName { get; set; }

        /// <summary>Host Operating System. (For example, Windows10, MacOS, RHEL, etc.).</summary>
        [Info(
            Required = false,
            ReadOnly = false,
            Description = @"Host Operating System. (For example, Windows10, MacOS, RHEL, etc.).",
            SerializedName = @"os",
            PossibleTypes = new[] {typeof(string)})]
        [Origin(PropertyOrigin.Owned)]
        public string OS { get; set; }

        /// <summary>
        ///     Private (not routable) IPv4 or IPv6 address (see RFC 1918) at the time of the alert.
        /// </summary>
        [Info(
            Required = false,
            ReadOnly = false,
            Description = @"Private (not routable) IPv4 or IPv6 address (see RFC 1918) at the time of the alert.",
            SerializedName = @"privateIpAddress",
            PossibleTypes = new[] {typeof(string)})]
        [Origin(PropertyOrigin.Owned)]
        public string PrivateIPAddress { get; set; }

        /// <summary>Publicly routable IPv4 or IPv6 address (see RFC 1918) at time of the alert.</summary>
        [Info(
            Required = false,
            ReadOnly = false,
            Description = @"Publicly routable IPv4 or IPv6 address (see RFC 1918) at time of the alert.",
            SerializedName = @"publicIpAddress",
            PossibleTypes = new[] {typeof(string)})]
        [Origin(PropertyOrigin.Owned)]
        public string PublicIPAddress { get; set; }

        /// <summary>
        ///     Provider-generated/calculated risk score of the host. Recommended value range of 0-1, which equates to a
        ///     percentage.
        /// </summary>
        [Info(
            Required = false,
            ReadOnly = false,
            Description =
                @"Provider-generated/calculated risk score of the host.  Recommended value range of 0-1, which equates to a percentage.",
            SerializedName = @"riskScore",
            PossibleTypes = new[] {typeof(string)})]
        [Origin(PropertyOrigin.Owned)]
        public string RiskScore { get; set; }
    }
}