// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6306, generator: {generator})
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Management.Automation;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Graph.PowerShell.Runtime;
using Microsoft.Graph.PowerShell.Runtime.Cmdlets;
using Microsoft.Graph.PowerShell.Runtime.PowerShell;
using Microsoft.Graph.PowerShell.Security.Models;
using Action = Microsoft.Graph.PowerShell.Security.Models.Action;

namespace Microsoft.Graph.PowerShell.Cmdlets
{
    using static Extensions;

    /// <summary>Create new navigation property to securityActions for security</summary>
    /// <remarks>
    ///     [OpenAPI] security_CreateSecurityActions=>POST:"/security/securityActions"
    /// </remarks>
    [Cmdlet(VerbsCommon.New, @"MgSecurityAction", SupportsShouldProcess = true)]
    [OutputType(typeof(Action))]
    [Description(@"Create new navigation property to securityActions for security")]
    public class NewMgSecurityAction : NewCmdletBase<Action>
    {
        protected override string Url => "https://graph.microsoft.com/beta/security/securityActions";
    }
}