// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6306, generator: {generator})
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using Microsoft.Graph.PowerShell.Runtime.Cmdlets;
using Microsoft.Graph.PowerShell.Security.Models;

namespace Microsoft.Graph.PowerShell.Security.Cmdlets
{
    /// <summary>Read-only. Nullable.</summary>
    /// <remarks>
    /// [OpenAPI] security_CreateAlerts=>POST:"/security/alerts"
    /// </remarks>
    [System.Management.Automation.Cmdlet(System.Management.Automation.VerbsCommon.New, @"MgSecurityAlert", SupportsShouldProcess = true)]
    [System.Management.Automation.OutputType(typeof(MicrosoftGraphAlert))]
    public class NewMgSecurityAlert : NewCmdletBase<MicrosoftGraphAlert>
    {
        protected override string Url => "https://graph.microsoft.com/beta/security/alerts/";
    }
}