// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>album</summary>
    public partial class MgAlbum
    {

        /// <summary>Backing field for <see cref="CoverImageItemId" /> property.</summary>
        private string _coverImageItemId;

        /// <summary>Unique identifier of the [driveItem][] that is the cover of the album.</summary>
        public string CoverImageItemId { get => this._coverImageItemId; set => this._coverImageItemId = value; }

    }
}