// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>alternativeSecurityId</summary>
    public partial class MgAlternativeSecurityId
    {

        /// <summary>Backing field for <see cref="IdentityProvider" /> property.</summary>
        private string _identityProvider;

        /// <summary>For internal use only</summary>
        public string IdentityProvider { get => this._identityProvider; set => this._identityProvider = value; }

        /// <summary>Backing field for <see cref="Key" /> property.</summary>
        private byte[] _key;

        /// <summary>For internal use only</summary>
        public byte[] Key { get => this._key; set => this._key = value; }

        /// <summary>Backing field for <see cref="Type" /> property.</summary>
        private int? _type;

        /// <summary>For internal use only</summary>
        public int? Type { get => this._type; set => this._type = value; }

    }
}