// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>assignedPlan</summary>
    public partial class MgAssignedPlan
    {

        /// <summary>Backing field for <see cref="AssignedDateTime" /> property.</summary>
        private global::System.DateTime? _assignedDateTime;

        /// <summary>
        /// The date and time at which the plan was assigned; for example: 2013-01-02T19:32:30Z. The Timestamp type represents date
        /// and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
        /// </summary>
        public global::System.DateTime? AssignedDateTime { get => this._assignedDateTime; set => this._assignedDateTime = value; }

        /// <summary>Backing field for <see cref="CapabilityStatus" /> property.</summary>
        private string _capabilityStatus;

        /// <summary>
        /// Condition of the capability assignment. The possible values are Enabled, Warning, Suspended, Deleted, LockedOut.
        /// </summary>
        public string CapabilityStatus { get => this._capabilityStatus; set => this._capabilityStatus = value; }

        /// <summary>Backing field for <see cref="Service" /> property.</summary>
        private string _service;

        /// <summary>The name of the service; for example, 'Exchange'.</summary>
        public string Service { get => this._service; set => this._service = value; }

        /// <summary>Backing field for <see cref="ServicePlanId" /> property.</summary>
        private string _servicePlanId;

        /// <summary>A GUID that identifies the service plan.</summary>
        public string ServicePlanId { get => this._servicePlanId; set => this._servicePlanId = value; }

    }
}