// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>attendanceRecord</summary>
    public partial class MgAttendanceRecord
    {

        /// <summary>Backing field for <see cref="AttendanceIntervals" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgAttendanceInterval[] _attendanceIntervals;

        /// <summary>List of time periods between joining and leaving.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgAttendanceInterval[] AttendanceIntervals { get => this._attendanceIntervals; set => this._attendanceIntervals = value; }

        /// <summary>Backing field for <see cref="EmailAddress" /> property.</summary>
        private string _emailAddress;

        /// <summary>Email address.</summary>
        public string EmailAddress { get => this._emailAddress; set => this._emailAddress = value; }

        /// <summary>Backing field for <see cref="Identity" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgIdentity _identity;

        /// <summary>identity</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentity Identity { get => (this._identity = this._identity ?? new Microsoft.Graph.PowerShell.Users.Models.MgIdentity()); set => this._identity = value; }

        /// <summary>Backing field for <see cref="Role" /> property.</summary>
        private string _role;

        /// <summary>
        /// Role of the attendee. Possible values are None, Attendee, Presenter, and Organizer.
        /// </summary>
        public string Role { get => this._role; set => this._role = value; }

        /// <summary>Backing field for <see cref="TotalAttendanceInSeconds" /> property.</summary>
        private int? _totalAttendanceInSeconds;

        /// <summary>Total duration of the attendances in seconds.</summary>
        public int? TotalAttendanceInSeconds { get => this._totalAttendanceInSeconds; set => this._totalAttendanceInSeconds = value; }

    }
}