// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>audio</summary>
    public partial class MgAudio
    {

        /// <summary>Backing field for <see cref="Album" /> property.</summary>
        private string _album;

        /// <summary>The title of the album for this audio file.</summary>
        public string Album { get => this._album; set => this._album = value; }

        /// <summary>Backing field for <see cref="AlbumArtist" /> property.</summary>
        private string _albumArtist;

        /// <summary>The artist named on the album for the audio file.</summary>
        public string AlbumArtist { get => this._albumArtist; set => this._albumArtist = value; }

        /// <summary>Backing field for <see cref="Artist" /> property.</summary>
        private string _artist;

        /// <summary>The performing artist for the audio file.</summary>
        public string Artist { get => this._artist; set => this._artist = value; }

        /// <summary>Backing field for <see cref="Bitrate" /> property.</summary>
        private long? _bitrate;

        /// <summary>Bitrate expressed in kbps.</summary>
        public long? Bitrate { get => this._bitrate; set => this._bitrate = value; }

        /// <summary>Backing field for <see cref="Composers" /> property.</summary>
        private string _composers;

        /// <summary>The name of the composer of the audio file.</summary>
        public string Composers { get => this._composers; set => this._composers = value; }

        /// <summary>Backing field for <see cref="Copyright" /> property.</summary>
        private string _copyright;

        /// <summary>Copyright information for the audio file.</summary>
        public string Copyright { get => this._copyright; set => this._copyright = value; }

        /// <summary>Backing field for <see cref="Disc" /> property.</summary>
        private int? _disc;

        /// <summary>The number of the disc this audio file came from.</summary>
        public int? Disc { get => this._disc; set => this._disc = value; }

        /// <summary>Backing field for <see cref="DiscCount" /> property.</summary>
        private int? _discCount;

        /// <summary>The total number of discs in this album.</summary>
        public int? DiscCount { get => this._discCount; set => this._discCount = value; }

        /// <summary>Backing field for <see cref="Duration" /> property.</summary>
        private long? _duration;

        /// <summary>Duration of the audio file, expressed in milliseconds</summary>
        public long? Duration { get => this._duration; set => this._duration = value; }

        /// <summary>Backing field for <see cref="Genre" /> property.</summary>
        private string _genre;

        /// <summary>The genre of this audio file.</summary>
        public string Genre { get => this._genre; set => this._genre = value; }

        /// <summary>Backing field for <see cref="HasDrm" /> property.</summary>
        private bool? _hasDrm;

        /// <summary>Indicates if the file is protected with digital rights management.</summary>
        public bool? HasDrm { get => this._hasDrm; set => this._hasDrm = value; }

        /// <summary>Backing field for <see cref="IsVariableBitrate" /> property.</summary>
        private bool? _isVariableBitrate;

        /// <summary>Indicates if the file is encoded with a variable bitrate.</summary>
        public bool? IsVariableBitrate { get => this._isVariableBitrate; set => this._isVariableBitrate = value; }

        /// <summary>Backing field for <see cref="Title" /> property.</summary>
        private string _title;

        /// <summary>The title of the audio file.</summary>
        public string Title { get => this._title; set => this._title = value; }

        /// <summary>Backing field for <see cref="Track" /> property.</summary>
        private int? _track;

        /// <summary>The number of the track on the original disc for this audio file.</summary>
        public int? Track { get => this._track; set => this._track = value; }

        /// <summary>Backing field for <see cref="TrackCount" /> property.</summary>
        private int? _trackCount;

        /// <summary>The total number of tracks on the original disc for this audio file.</summary>
        public int? TrackCount { get => this._trackCount; set => this._trackCount = value; }

        /// <summary>Backing field for <see cref="Year" /> property.</summary>
        private int? _year;

        /// <summary>The year the audio file was recorded.</summary>
        public int? Year { get => this._year; set => this._year = value; }

    }
}