// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>bitlocker</summary>
    public partial class MgBitlocker
    {

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="RecoveryKeys" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgBitlockerRecoveryKey[] _recoveryKeys;

        /// <summary>The recovery keys associated with the bitlocker entity.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgBitlockerRecoveryKey[] RecoveryKeys { get => this._recoveryKeys; set => this._recoveryKeys = value; }

    }
}