// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>chatViewpoint</summary>
    public partial class MgChatViewpoint
    {

        /// <summary>Backing field for <see cref="LastMessageReadDateTime" /> property.</summary>
        private global::System.DateTime? _lastMessageReadDateTime;

        /// <summary>
        /// Represents the dateTime up until which the calling user has read chatMessages in a specific chat.
        /// </summary>
        public global::System.DateTime? LastMessageReadDateTime { get => this._lastMessageReadDateTime; set => this._lastMessageReadDateTime = value; }

    }
}