// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>channel</summary>
    public partial class MgChannel
    {

        /// <summary>Backing field for <see cref="CreatedDateTime" /> property.</summary>
        private global::System.DateTime? _createdDateTime;

        /// <summary>Read only. Timestamp at which the channel was created.</summary>
        public global::System.DateTime? CreatedDateTime { get => this._createdDateTime; set => this._createdDateTime = value; }

        /// <summary>Backing field for <see cref="Description" /> property.</summary>
        private string _description;

        /// <summary>Optional textual description for the channel.</summary>
        public string Description { get => this._description; set => this._description = value; }

        /// <summary>Backing field for <see cref="DisplayName" /> property.</summary>
        private string _displayName;

        /// <summary>Channel name as it will appear to the user in Microsoft Teams.</summary>
        public string DisplayName { get => this._displayName; set => this._displayName = value; }

        /// <summary>Backing field for <see cref="Email" /> property.</summary>
        private string _email;

        /// <summary>The email address for sending messages to the channel. Read-only.</summary>
        public string Email { get => this._email; set => this._email = value; }

        /// <summary>Backing field for <see cref="FilesFolder" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgDriveItem _filesFolder;

        /// <summary>driveItem</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgDriveItem FilesFolder { get => (this._filesFolder = this._filesFolder ?? new Microsoft.Graph.PowerShell.Users.Models.MgDriveItem()); set => this._filesFolder = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="IsFavoriteByDefault" /> property.</summary>
        private bool? _isFavoriteByDefault;

        /// <summary>
        /// Indicates whether the channel should automatically be marked 'favorite' for all members of the team. Can only be set programmatically
        /// with Create team. Default: false.
        /// </summary>
        public bool? IsFavoriteByDefault { get => this._isFavoriteByDefault; set => this._isFavoriteByDefault = value; }

        /// <summary>Backing field for <see cref="Members" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgConversationMember[] _members;

        /// <summary>A collection of membership records associated with the channel.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgConversationMember[] Members { get => this._members; set => this._members = value; }

        /// <summary>Backing field for <see cref="MembershipType" /> property.</summary>
        private string _membershipType;

        /// <summary>channelMembershipType</summary>
        public string MembershipType { get => this._membershipType; set => this._membershipType = value; }

        /// <summary>Backing field for <see cref="Messages" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgChatMessage[] _messages;

        /// <summary>
        /// A collection of all the messages in the channel. A navigation property. Nullable.
        /// </summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgChatMessage[] Messages { get => this._messages; set => this._messages = value; }

        /// <summary>Backing field for <see cref="ModerationSettings" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgChannelModerationSettings _moderationSettings;

        /// <summary>channelModerationSettings</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgChannelModerationSettings ModerationSettings { get => (this._moderationSettings = this._moderationSettings ?? new Microsoft.Graph.PowerShell.Users.Models.MgChannelModerationSettings()); set => this._moderationSettings = value; }

        /// <summary>Backing field for <see cref="Tabs" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgTeamsTab[] _tabs;

        /// <summary>A collection of all the tabs in the channel. A navigation property.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgTeamsTab[] Tabs { get => this._tabs; set => this._tabs = value; }

        /// <summary>Backing field for <see cref="WebUrl" /> property.</summary>
        private string _webUrl;

        /// <summary>
        /// A hyperlink that will go to the channel in Microsoft Teams. This is the URL that you get when you right-click a channel
        /// in Microsoft Teams and select Get link to channel. This URL should be treated as an opaque blob, and not parsed. Read-only.
        /// </summary>
        public string WebUrl { get => this._webUrl; set => this._webUrl = value; }

    }
}