// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>contact</summary>
    public partial class MgContact
    {

        /// <summary>Backing field for <see cref="AssistantName" /> property.</summary>
        private string _assistantName;

        /// <summary>The name of the contact's assistant.</summary>
        public string AssistantName { get => this._assistantName; set => this._assistantName = value; }

        /// <summary>Backing field for <see cref="Birthday" /> property.</summary>
        private global::System.DateTime? _birthday;

        /// <summary>
        /// The contact's birthday. The Timestamp type represents date and time information using ISO 8601 format and is always in
        /// UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
        /// </summary>
        public global::System.DateTime? Birthday { get => this._birthday; set => this._birthday = value; }

        /// <summary>The categories associated with the item</summary>
        public string[] Categories { get; set; }

        /// <summary>
        /// Identifies the version of the item. Every time the item is changed, changeKey changes as well. This allows Exchange to
        /// apply changes to the correct version of the object. Read-only.
        /// </summary>
        public string ChangeKey { get; set; }

        /// <summary>Backing field for <see cref="Children" /> property.</summary>
        private string[] _children;

        /// <summary>The names of the contact's children.</summary>
        public string[] Children { get => this._children; set => this._children = value; }

        /// <summary>Backing field for <see cref="CompanyName" /> property.</summary>
        private string _companyName;

        /// <summary>The name of the contact's company.</summary>
        public string CompanyName { get => this._companyName; set => this._companyName = value; }

        /// <summary>
        /// The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example,
        /// midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
        /// </summary>
        public global::System.DateTime? CreatedDateTime { get; set; }

        /// <summary>Backing field for <see cref="Department" /> property.</summary>
        private string _department;

        /// <summary>The contact's department.</summary>
        public string Department { get => this._department; set => this._department = value; }

        /// <summary>Backing field for <see cref="DisplayName" /> property.</summary>
        private string _displayName;

        /// <summary>
        /// The contact's display name. You can specify the display name in a create or update operation. Note that later updates
        /// to other properties may cause an automatically generated value to overwrite the displayName value you have specified.
        /// To preserve a pre-existing value, always include it as displayName in an update operation.
        /// </summary>
        public string DisplayName { get => this._displayName; set => this._displayName = value; }

        /// <summary>Backing field for <see cref="EmailAddresses" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgTypedEmailAddress[] _emailAddresses;

        /// <summary>The contact's email addresses.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgTypedEmailAddress[] EmailAddresses { get => this._emailAddresses; set => this._emailAddresses = value; }

        /// <summary>Backing field for <see cref="Extensions" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgExtension[] _extensions;

        /// <summary>The collection of open extensions defined for the contact. Nullable.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgExtension[] Extensions { get => this._extensions; set => this._extensions = value; }

        /// <summary>Backing field for <see cref="FileAs" /> property.</summary>
        private string _fileAs;

        /// <summary>The name the contact is filed under.</summary>
        public string FileAs { get => this._fileAs; set => this._fileAs = value; }

        /// <summary>Backing field for <see cref="Flag" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgFollowupFlag _flag;

        /// <summary>followupFlag</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgFollowupFlag Flag { get => (this._flag = this._flag ?? new Microsoft.Graph.PowerShell.Users.Models.MgFollowupFlag()); set => this._flag = value; }

        /// <summary>Backing field for <see cref="Gender" /> property.</summary>
        private string _gender;

        /// <summary>The contact's gender.</summary>
        public string Gender { get => this._gender; set => this._gender = value; }

        /// <summary>Backing field for <see cref="Generation" /> property.</summary>
        private string _generation;

        /// <summary>The contact's generation.</summary>
        public string Generation { get => this._generation; set => this._generation = value; }

        /// <summary>Backing field for <see cref="GivenName" /> property.</summary>
        private string _givenName;

        /// <summary>The contact's given name.</summary>
        public string GivenName { get => this._givenName; set => this._givenName = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="ImAddresses" /> property.</summary>
        private string[] _imAddresses;

        /// <summary>The contact's instant messaging (IM) addresses.</summary>
        public string[] ImAddresses { get => this._imAddresses; set => this._imAddresses = value; }

        /// <summary>Backing field for <see cref="Initials" /> property.</summary>
        private string _initials;

        /// <summary>The contact's initials.</summary>
        public string Initials { get => this._initials; set => this._initials = value; }

        /// <summary>Backing field for <see cref="IsFavorite" /> property.</summary>
        private bool? _isFavorite;

        public bool? IsFavorite { get => this._isFavorite; set => this._isFavorite = value; }

        /// <summary>Backing field for <see cref="JobTitle" /> property.</summary>
        private string _jobTitle;

        /// <summary>The contact’s job title.</summary>
        public string JobTitle { get => this._jobTitle; set => this._jobTitle = value; }

        /// <summary>
        /// The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example,
        /// midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
        /// </summary>
        public global::System.DateTime? LastModifiedDateTime { get; set; }

        /// <summary>Backing field for <see cref="Manager" /> property.</summary>
        private string _manager;

        /// <summary>The name of the contact's manager.</summary>
        public string Manager { get => this._manager; set => this._manager = value; }

        /// <summary>Backing field for <see cref="MiddleName" /> property.</summary>
        private string _middleName;

        /// <summary>The contact's middle name.</summary>
        public string MiddleName { get => this._middleName; set => this._middleName = value; }

        /// <summary>Backing field for <see cref="MultiValueExtendedProperties" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgMultiValueLegacyExtendedProperty[] _multiValueExtendedProperties;

        /// <summary>
        /// The collection of multi-value extended properties defined for the contact. Read-only. Nullable.
        /// </summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgMultiValueLegacyExtendedProperty[] MultiValueExtendedProperties { get => this._multiValueExtendedProperties; set => this._multiValueExtendedProperties = value; }

        /// <summary>Backing field for <see cref="NickName" /> property.</summary>
        private string _nickName;

        /// <summary>The contact's nickname.</summary>
        public string NickName { get => this._nickName; set => this._nickName = value; }

        /// <summary>Backing field for <see cref="OfficeLocation" /> property.</summary>
        private string _officeLocation;

        /// <summary>The location of the contact's office.</summary>
        public string OfficeLocation { get => this._officeLocation; set => this._officeLocation = value; }

        /// <summary>Backing field for <see cref="ParentFolderId" /> property.</summary>
        private string _parentFolderId;

        /// <summary>The ID of the contact's parent folder.</summary>
        public string ParentFolderId { get => this._parentFolderId; set => this._parentFolderId = value; }

        /// <summary>Backing field for <see cref="PersonalNotes" /> property.</summary>
        private string _personalNotes;

        /// <summary>The user's notes about the contact.</summary>
        public string PersonalNotes { get => this._personalNotes; set => this._personalNotes = value; }

        /// <summary>Backing field for <see cref="Phones" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgPhone[] _phones;

        public Microsoft.Graph.PowerShell.Users.Models.MgPhone[] Phones { get => this._phones; set => this._phones = value; }

        /// <summary>Backing field for <see cref="Photo" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgProfilePhoto _photo;

        /// <summary>profilePhoto</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgProfilePhoto Photo { get => (this._photo = this._photo ?? new Microsoft.Graph.PowerShell.Users.Models.MgProfilePhoto()); set => this._photo = value; }

        /// <summary>Backing field for <see cref="PostalAddresses" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgPhysicalAddress[] _postalAddresses;

        public Microsoft.Graph.PowerShell.Users.Models.MgPhysicalAddress[] PostalAddresses { get => this._postalAddresses; set => this._postalAddresses = value; }

        /// <summary>Backing field for <see cref="Profession" /> property.</summary>
        private string _profession;

        /// <summary>The contact's profession.</summary>
        public string Profession { get => this._profession; set => this._profession = value; }

        /// <summary>Backing field for <see cref="SingleValueExtendedProperties" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgSingleValueLegacyExtendedProperty[] _singleValueExtendedProperties;

        /// <summary>
        /// The collection of single-value extended properties defined for the contact. Read-only. Nullable.
        /// </summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgSingleValueLegacyExtendedProperty[] SingleValueExtendedProperties { get => this._singleValueExtendedProperties; set => this._singleValueExtendedProperties = value; }

        /// <summary>Backing field for <see cref="SpouseName" /> property.</summary>
        private string _spouseName;

        /// <summary>The name of the contact's spouse/partner.</summary>
        public string SpouseName { get => this._spouseName; set => this._spouseName = value; }

        /// <summary>Backing field for <see cref="Surname" /> property.</summary>
        private string _surname;

        /// <summary>The contact's surname.</summary>
        public string Surname { get => this._surname; set => this._surname = value; }

        /// <summary>Backing field for <see cref="Title" /> property.</summary>
        private string _title;

        /// <summary>The contact's title.</summary>
        public string Title { get => this._title; set => this._title = value; }

        /// <summary>Backing field for <see cref="Websites" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgWebsite[] _websites;

        public Microsoft.Graph.PowerShell.Users.Models.MgWebsite[] Websites { get => this._websites; set => this._websites = value; }

        /// <summary>Backing field for <see cref="WeddingAnniversary" /> property.</summary>
        private global::System.DateTime? _weddingAnniversary;

        public global::System.DateTime? WeddingAnniversary { get => this._weddingAnniversary; set => this._weddingAnniversary = value; }

        /// <summary>Backing field for <see cref="YomiCompanyName" /> property.</summary>
        private string _yomiCompanyName;

        /// <summary>The phonetic Japanese company name of the contact.</summary>
        public string YomiCompanyName { get => this._yomiCompanyName; set => this._yomiCompanyName = value; }

        /// <summary>Backing field for <see cref="YomiGivenName" /> property.</summary>
        private string _yomiGivenName;

        /// <summary>The phonetic Japanese given name (first name) of the contact.</summary>
        public string YomiGivenName { get => this._yomiGivenName; set => this._yomiGivenName = value; }

        /// <summary>Backing field for <see cref="YomiSurname" /> property.</summary>
        private string _yomiSurname;

        /// <summary>The phonetic Japanese surname (last name) of the contact.</summary>
        public string YomiSurname { get => this._yomiSurname; set => this._yomiSurname = value; }

    }
}