// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>driveItemVersion</summary>
    public partial class MgDriveItemVersion
    {

        /// <summary>Backing field for <see cref="Content" /> property.</summary>
        private byte[] _content;

        public byte[] Content { get => this._content; set => this._content = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet LastModifiedBy { get; set; }

        /// <summary>Date and time the version was last modified. Read-only.</summary>
        public global::System.DateTime? LastModifiedDateTime { get; set; }

        /// <summary>publicationFacet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgPublicationFacet Publication { get; set; }

        /// <summary>Backing field for <see cref="Size" /> property.</summary>
        private long? _size;

        /// <summary>Indicates the size of the content stream for this version of the item.</summary>
        public long? Size { get => this._size; set => this._size = value; }

    }
}