// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>Enrollment Configuration Assignment</summary>
    public partial class MgEnrollmentConfigurationAssignment
    {

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="Source" /> property.</summary>
        private string _source;

        /// <summary>deviceAndAppManagementAssignmentSource</summary>
        public string Source { get => this._source; set => this._source = value; }

        /// <summary>Backing field for <see cref="SourceId" /> property.</summary>
        private string _sourceId;

        /// <summary>Identifier for resource used for deployment to a group</summary>
        public string SourceId { get => this._sourceId; set => this._sourceId = value; }

        /// <summary>Backing field for <see cref="Target" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgDeviceAndAppManagementAssignmentTarget _target;

        /// <summary>Base type for assignment targets.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgDeviceAndAppManagementAssignmentTarget Target { get => (this._target = this._target ?? new Microsoft.Graph.PowerShell.Users.Models.MgDeviceAndAppManagementAssignmentTarget()); set => this._target = value; }

    }
}