// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>geoCoordinates</summary>
    public partial class MgGeoCoordinates
    {

        /// <summary>Backing field for <see cref="Altitude" /> property.</summary>
        private double? _altitude;

        /// <summary>
        /// Optional. The altitude (height), in feet, above sea level for the item. Read-only.
        /// </summary>
        public double? Altitude { get => this._altitude; set => this._altitude = value; }

        /// <summary>Backing field for <see cref="Latitude" /> property.</summary>
        private double? _latitude;

        /// <summary>
        /// Optional. The latitude, in decimal, for the item. Writable on OneDrive Personal.
        /// </summary>
        public double? Latitude { get => this._latitude; set => this._latitude = value; }

        /// <summary>Backing field for <see cref="Longitude" /> property.</summary>
        private double? _longitude;

        /// <summary>
        /// Optional. The longitude, in decimal, for the item. Writable on OneDrive Personal.
        /// </summary>
        public double? Longitude { get => this._longitude; set => this._longitude = value; }

    }
}