// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>image</summary>
    public partial class MgImage
    {

        /// <summary>Backing field for <see cref="Height" /> property.</summary>
        private int? _height;

        /// <summary>Optional. Height of the image, in pixels. Read-only.</summary>
        public int? Height { get => this._height; set => this._height = value; }

        /// <summary>Backing field for <see cref="Width" /> property.</summary>
        private int? _width;

        /// <summary>Optional. Width of the image, in pixels. Read-only.</summary>
        public int? Width { get => this._width; set => this._width = value; }

    }
}