// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>inferenceClassificationOverride</summary>
    public partial class MgInferenceClassificationOverride
    {

        /// <summary>Backing field for <see cref="ClassifyAs" /> property.</summary>
        private string _classifyAs;

        /// <summary>inferenceClassificationType</summary>
        public string ClassifyAs { get => this._classifyAs; set => this._classifyAs = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="SenderEmailAddress" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgEmailAddress _senderEmailAddress;

        /// <summary>emailAddress</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgEmailAddress SenderEmailAddress { get => (this._senderEmailAddress = this._senderEmailAddress ?? new Microsoft.Graph.PowerShell.Users.Models.MgEmailAddress()); set => this._senderEmailAddress = value; }

    }
}