// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>itemAddress</summary>
    public partial class MgItemAddress
    {

        /// <summary>allowedAudiences</summary>
        public string AllowedAudiences { get; set; }

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet CreatedBy { get; set; }

        /// <summary>Provides the dateTimeOffset for when the entity was created.</summary>
        public global::System.DateTime? CreatedDateTime { get; set; }

        /// <summary>Backing field for <see cref="Detail" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgPhysicalAddress _detail;

        /// <summary>physicalAddress</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgPhysicalAddress Detail { get => (this._detail = this._detail ?? new Microsoft.Graph.PowerShell.Users.Models.MgPhysicalAddress()); set => this._detail = value; }

        /// <summary>Backing field for <see cref="DisplayName" /> property.</summary>
        private string _displayName;

        /// <summary>Friendly name the user has assigned to this address.</summary>
        public string DisplayName { get => this._displayName; set => this._displayName = value; }

        /// <summary>Backing field for <see cref="GeoCoordinates" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgGeoCoordinates _geoCoordinates;

        /// <summary>geoCoordinates</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgGeoCoordinates GeoCoordinates { get => (this._geoCoordinates = this._geoCoordinates ?? new Microsoft.Graph.PowerShell.Users.Models.MgGeoCoordinates()); set => this._geoCoordinates = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>inferenceData</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgInferenceData Inference { get; set; }

        public bool? IsSearchable { get; set; }

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet LastModifiedBy { get; set; }

        /// <summary>Provides the dateTimeOffset for when the entity was created.</summary>
        public global::System.DateTime? LastModifiedDateTime { get; set; }

        /// <summary>personDataSources</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgPersonDataSources Source { get; set; }

    }
}