// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>itemActivityOLD</summary>
    public partial class MgItemActivityOld
    {

        /// <summary>Backing field for <see cref="Action" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgItemActionSet _action;

        /// <summary>itemActionSet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgItemActionSet Action { get => (this._action = this._action ?? new Microsoft.Graph.PowerShell.Users.Models.MgItemActionSet()); set => this._action = value; }

        /// <summary>Backing field for <see cref="Actor" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet _actor;

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet Actor { get => (this._actor = this._actor ?? new Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet()); set => this._actor = value; }

        /// <summary>Backing field for <see cref="DriveItem" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgDriveItem _driveItem;

        /// <summary>driveItem</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgDriveItem DriveItem { get => (this._driveItem = this._driveItem ?? new Microsoft.Graph.PowerShell.Users.Models.MgDriveItem()); set => this._driveItem = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="ListItem" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgListItem _listItem;

        /// <summary>listItem</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgListItem ListItem { get => (this._listItem = this._listItem ?? new Microsoft.Graph.PowerShell.Users.Models.MgListItem()); set => this._listItem = value; }

        /// <summary>Backing field for <see cref="Times" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgItemActivityTimeSet _times;

        /// <summary>itemActivityTimeSet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgItemActivityTimeSet Times { get => (this._times = this._times ?? new Microsoft.Graph.PowerShell.Users.Models.MgItemActivityTimeSet()); set => this._times = value; }

    }
}