// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>itemFacet</summary>
    public partial class MgItemFacet
    {

        /// <summary>Backing field for <see cref="AllowedAudiences" /> property.</summary>
        private string _allowedAudiences;

        /// <summary>allowedAudiences</summary>
        public string AllowedAudiences { get => this._allowedAudiences; set => this._allowedAudiences = value; }

        /// <summary>Backing field for <see cref="CreatedBy" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet _createdBy;

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet CreatedBy { get => (this._createdBy = this._createdBy ?? new Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet()); set => this._createdBy = value; }

        /// <summary>Backing field for <see cref="CreatedDateTime" /> property.</summary>
        private global::System.DateTime? _createdDateTime;

        /// <summary>Provides the dateTimeOffset for when the entity was created.</summary>
        public global::System.DateTime? CreatedDateTime { get => this._createdDateTime; set => this._createdDateTime = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="Inference" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgInferenceData _inference;

        /// <summary>inferenceData</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgInferenceData Inference { get => (this._inference = this._inference ?? new Microsoft.Graph.PowerShell.Users.Models.MgInferenceData()); set => this._inference = value; }

        /// <summary>Backing field for <see cref="IsSearchable" /> property.</summary>
        private bool? _isSearchable;

        public bool? IsSearchable { get => this._isSearchable; set => this._isSearchable = value; }

        /// <summary>Backing field for <see cref="LastModifiedBy" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet _lastModifiedBy;

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet LastModifiedBy { get => (this._lastModifiedBy = this._lastModifiedBy ?? new Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet()); set => this._lastModifiedBy = value; }

        /// <summary>Backing field for <see cref="LastModifiedDateTime" /> property.</summary>
        private global::System.DateTime? _lastModifiedDateTime;

        /// <summary>Provides the dateTimeOffset for when the entity was created.</summary>
        public global::System.DateTime? LastModifiedDateTime { get => this._lastModifiedDateTime; set => this._lastModifiedDateTime = value; }

        /// <summary>Backing field for <see cref="Source" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgPersonDataSources _source;

        /// <summary>personDataSources</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgPersonDataSources Source { get => (this._source = this._source ?? new Microsoft.Graph.PowerShell.Users.Models.MgPersonDataSources()); set => this._source = value; }

    }
}