// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>languageProficiency</summary>
    public partial class MgLanguageProficiency
    {

        /// <summary>allowedAudiences</summary>
        public string AllowedAudiences { get; set; }

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet CreatedBy { get; set; }

        /// <summary>Provides the dateTimeOffset for when the entity was created.</summary>
        public global::System.DateTime? CreatedDateTime { get; set; }

        /// <summary>Backing field for <see cref="DisplayName" /> property.</summary>
        private string _displayName;

        /// <summary>Contains the long-form name for the language.</summary>
        public string DisplayName { get => this._displayName; set => this._displayName = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>inferenceData</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgInferenceData Inference { get; set; }

        public bool? IsSearchable { get; set; }

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet LastModifiedBy { get; set; }

        /// <summary>Provides the dateTimeOffset for when the entity was created.</summary>
        public global::System.DateTime? LastModifiedDateTime { get; set; }

        /// <summary>Backing field for <see cref="Proficiency" /> property.</summary>
        private string _proficiency;

        /// <summary>languageProficiencyLevel</summary>
        public string Proficiency { get => this._proficiency; set => this._proficiency = value; }

        /// <summary>Backing field for <see cref="Reading" /> property.</summary>
        private string _reading;

        /// <summary>languageProficiencyLevel</summary>
        public string Reading { get => this._reading; set => this._reading = value; }

        /// <summary>personDataSources</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgPersonDataSources Source { get; set; }

        /// <summary>Backing field for <see cref="Spoken" /> property.</summary>
        private string _spoken;

        /// <summary>languageProficiencyLevel</summary>
        public string Spoken { get => this._spoken; set => this._spoken = value; }

        /// <summary>Backing field for <see cref="Tag" /> property.</summary>
        private string _tag;

        /// <summary>Contains the four-character BCP47 name for the language (en-US, no-NB, en-AU).</summary>
        public string Tag { get => this._tag; set => this._tag = value; }

        /// <summary>Backing field for <see cref="ThumbnailUrl" /> property.</summary>
        private string _thumbnailUrl;

        public string ThumbnailUrl { get => this._thumbnailUrl; set => this._thumbnailUrl = value; }

        /// <summary>Backing field for <see cref="Written" /> property.</summary>
        private string _written;

        /// <summary>languageProficiencyLevel</summary>
        public string Written { get => this._written; set => this._written = value; }

    }
}