// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>licenseAssignmentState</summary>
    public partial class MgLicenseAssignmentState
    {

        /// <summary>Backing field for <see cref="AssignedByGroup" /> property.</summary>
        private string _assignedByGroup;

        /// <summary>
        /// The id of the group that assigns this license. If the assignment is a direct-assigned license, this field will be Null.
        /// Read-Only.
        /// </summary>
        public string AssignedByGroup { get => this._assignedByGroup; set => this._assignedByGroup = value; }

        /// <summary>Backing field for <see cref="DisabledPlans" /> property.</summary>
        private string[] _disabledPlans;

        /// <summary>The service plans that are disabled in this assignment. Read-Only.</summary>
        public string[] DisabledPlans { get => this._disabledPlans; set => this._disabledPlans = value; }

        /// <summary>Backing field for <see cref="Error" /> property.</summary>
        private string _error;

        /// <summary>
        /// License assignment failure error. If the license is assigned successfully, this field will be Null. Read-Only. Possible
        /// values: CountViolation, MutuallyExclusiveViolation, DependencyViolation, ProhibitedInUsageLocationViolation, UniquenessViolation,
        /// and Others. For more information on how to identify and resolve license assignment errors see here.
        /// </summary>
        public string Error { get => this._error; set => this._error = value; }

        /// <summary>Backing field for <see cref="SkuId" /> property.</summary>
        private string _skuId;

        /// <summary>The unique identifier for the SKU. Read-Only.</summary>
        public string SkuId { get => this._skuId; set => this._skuId = value; }

        /// <summary>Backing field for <see cref="State" /> property.</summary>
        private string _state;

        /// <summary>
        /// Indicate the current state of this assignment. Read-Only. Possible values: Active, ActiveWithError, Disabled and Error.
        /// </summary>
        public string State { get => this._state; set => this._state = value; }

    }
}