// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>lobbyBypassSettings</summary>
    public partial class MgLobbyBypassSettings
    {

        /// <summary>Backing field for <see cref="IsDialInBypassEnabled" /> property.</summary>
        private bool? _isDialInBypassEnabled;

        /// <summary>
        /// Specifies whether or not to always let dial-in callers bypass the lobby. Optional.
        /// </summary>
        public bool? IsDialInBypassEnabled { get => this._isDialInBypassEnabled; set => this._isDialInBypassEnabled = value; }

        /// <summary>Backing field for <see cref="Scope" /> property.</summary>
        private string _scope;

        /// <summary>lobbyBypassScope</summary>
        public string Scope { get => this._scope; set => this._scope = value; }

    }
}