// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>
    /// The ManagedAppEntity is the base entity type for all other entity types under app management workflow.
    /// </summary>
    public partial class MgManagedAppRegistration
    {

        /// <summary>Backing field for <see cref="AppIdentifier" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgMobileAppIdentifier _appIdentifier;

        /// <summary>The identifier for a mobile app.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgMobileAppIdentifier AppIdentifier { get => (this._appIdentifier = this._appIdentifier ?? new Microsoft.Graph.PowerShell.Users.Models.MgMobileAppIdentifier()); set => this._appIdentifier = value; }

        /// <summary>Backing field for <see cref="ApplicationVersion" /> property.</summary>
        private string _applicationVersion;

        /// <summary>App version</summary>
        public string ApplicationVersion { get => this._applicationVersion; set => this._applicationVersion = value; }

        /// <summary>Backing field for <see cref="AppliedPolicies" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgManagedAppPolicy[] _appliedPolicies;

        /// <summary>
        /// Zero or more policys already applied on the registered app when it last synchronized with managment service.
        /// </summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgManagedAppPolicy[] AppliedPolicies { get => this._appliedPolicies; set => this._appliedPolicies = value; }

        /// <summary>Backing field for <see cref="AzureAdDeviceId" /> property.</summary>
        private string _azureAdDeviceId;

        /// <summary>
        /// The Azure Active Directory Device identifier of the host device. Value could be empty even when the host device is Azure
        /// Active Directory registered.
        /// </summary>
        public string AzureAdDeviceId { get => this._azureAdDeviceId; set => this._azureAdDeviceId = value; }

        /// <summary>Backing field for <see cref="CreatedDateTime" /> property.</summary>
        private global::System.DateTime? _createdDateTime;

        /// <summary>Date and time of creation</summary>
        public global::System.DateTime? CreatedDateTime { get => this._createdDateTime; set => this._createdDateTime = value; }

        /// <summary>Backing field for <see cref="DeviceManufacturer" /> property.</summary>
        private string _deviceManufacturer;

        /// <summary>The device manufacturer for the current app registration</summary>
        public string DeviceManufacturer { get => this._deviceManufacturer; set => this._deviceManufacturer = value; }

        /// <summary>Backing field for <see cref="DeviceModel" /> property.</summary>
        private string _deviceModel;

        /// <summary>The device model for the current app registration</summary>
        public string DeviceModel { get => this._deviceModel; set => this._deviceModel = value; }

        /// <summary>Backing field for <see cref="DeviceName" /> property.</summary>
        private string _deviceName;

        /// <summary>Host device name</summary>
        public string DeviceName { get => this._deviceName; set => this._deviceName = value; }

        /// <summary>Backing field for <see cref="DeviceTag" /> property.</summary>
        private string _deviceTag;

        /// <summary>
        /// App management SDK generated tag, which helps relate apps hosted on the same device. Not guaranteed to relate apps in
        /// all conditions.
        /// </summary>
        public string DeviceTag { get => this._deviceTag; set => this._deviceTag = value; }

        /// <summary>Backing field for <see cref="DeviceType" /> property.</summary>
        private string _deviceType;

        /// <summary>Host device type</summary>
        public string DeviceType { get => this._deviceType; set => this._deviceType = value; }

        /// <summary>Backing field for <see cref="FlaggedReasons" /> property.</summary>
        private string[] _flaggedReasons;

        /// <summary>
        /// Zero or more reasons an app registration is flagged. E.g. app running on rooted device
        /// </summary>
        public string[] FlaggedReasons { get => this._flaggedReasons; set => this._flaggedReasons = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="IntendedPolicies" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgManagedAppPolicy[] _intendedPolicies;

        /// <summary>Zero or more policies admin intended for the app as of now.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgManagedAppPolicy[] IntendedPolicies { get => this._intendedPolicies; set => this._intendedPolicies = value; }

        /// <summary>Backing field for <see cref="LastSyncDateTime" /> property.</summary>
        private global::System.DateTime? _lastSyncDateTime;

        /// <summary>Date and time of last the app synced with management service.</summary>
        public global::System.DateTime? LastSyncDateTime { get => this._lastSyncDateTime; set => this._lastSyncDateTime = value; }

        /// <summary>Backing field for <see cref="ManagedDeviceId" /> property.</summary>
        private string _managedDeviceId;

        /// <summary>
        /// The Managed Device identifier of the host device. Value could be empty even when the host device is managed.
        /// </summary>
        public string ManagedDeviceId { get => this._managedDeviceId; set => this._managedDeviceId = value; }

        /// <summary>Backing field for <see cref="ManagementSdkVersion" /> property.</summary>
        private string _managementSdkVersion;

        /// <summary>App management SDK version</summary>
        public string ManagementSdkVersion { get => this._managementSdkVersion; set => this._managementSdkVersion = value; }

        /// <summary>Backing field for <see cref="Operations" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgManagedAppOperation[] _operations;

        /// <summary>Zero or more long running operations triggered on the app registration.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgManagedAppOperation[] Operations { get => this._operations; set => this._operations = value; }

        /// <summary>Backing field for <see cref="PlatformVersion" /> property.</summary>
        private string _platformVersion;

        /// <summary>Operating System version</summary>
        public string PlatformVersion { get => this._platformVersion; set => this._platformVersion = value; }

        /// <summary>Backing field for <see cref="UserId" /> property.</summary>
        private string _userId;

        /// <summary>The user Id to who this app registration belongs.</summary>
        public string UserId { get => this._userId; set => this._userId = value; }

        /// <summary>Backing field for <see cref="Version" /> property.</summary>
        private string _version;

        /// <summary>Version of the entity.</summary>
        public string Version { get => this._version; set => this._version = value; }

    }
}