// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>Devices that are managed or pre-enrolled through Intune</summary>
    public partial class MgManagedDevice
    {

        /// <summary>Backing field for <see cref="AadRegistered" /> property.</summary>
        private bool? _aadRegistered;

        /// <summary>
        /// Whether the device is Azure Active Directory registered. This property is read-only.
        /// </summary>
        public bool? AadRegistered { get => this._aadRegistered; set => this._aadRegistered = value; }

        /// <summary>Backing field for <see cref="ActivationLockBypassCode" /> property.</summary>
        private string _activationLockBypassCode;

        /// <summary>
        /// Code that allows the Activation Lock on a device to be bypassed. This property is read-only.
        /// </summary>
        public string ActivationLockBypassCode { get => this._activationLockBypassCode; set => this._activationLockBypassCode = value; }

        /// <summary>Backing field for <see cref="AndroidSecurityPatchLevel" /> property.</summary>
        private string _androidSecurityPatchLevel;

        /// <summary>Android security patch level. This property is read-only.</summary>
        public string AndroidSecurityPatchLevel { get => this._androidSecurityPatchLevel; set => this._androidSecurityPatchLevel = value; }

        /// <summary>
        /// Backing field for <see cref="AssignmentFilterEvaluationStatusDetails" /> property.
        /// </summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgAssignmentFilterEvaluationStatusDetails[] _assignmentFilterEvaluationStatusDetails;

        /// <summary>Managed device mobile app configuration states for this device.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgAssignmentFilterEvaluationStatusDetails[] AssignmentFilterEvaluationStatusDetails { get => this._assignmentFilterEvaluationStatusDetails; set => this._assignmentFilterEvaluationStatusDetails = value; }

        /// <summary>Backing field for <see cref="AutopilotEnrolled" /> property.</summary>
        private bool? _autopilotEnrolled;

        /// <summary>
        /// Reports if the managed device is enrolled via auto-pilot. This property is read-only.
        /// </summary>
        public bool? AutopilotEnrolled { get => this._autopilotEnrolled; set => this._autopilotEnrolled = value; }

        /// <summary>Backing field for <see cref="AzureActiveDirectoryDeviceId" /> property.</summary>
        private string _azureActiveDirectoryDeviceId;

        /// <summary>
        /// The unique identifier for the Azure Active Directory device. Read only. This property is read-only.
        /// </summary>
        public string AzureActiveDirectoryDeviceId { get => this._azureActiveDirectoryDeviceId; set => this._azureActiveDirectoryDeviceId = value; }

        /// <summary>Backing field for <see cref="AzureAdDeviceId" /> property.</summary>
        private string _azureAdDeviceId;

        /// <summary>
        /// The unique identifier for the Azure Active Directory device. Read only. This property is read-only.
        /// </summary>
        public string AzureAdDeviceId { get => this._azureAdDeviceId; set => this._azureAdDeviceId = value; }

        /// <summary>Backing field for <see cref="AzureAdRegistered" /> property.</summary>
        private bool? _azureAdRegistered;

        /// <summary>
        /// Whether the device is Azure Active Directory registered. This property is read-only.
        /// </summary>
        public bool? AzureAdRegistered { get => this._azureAdRegistered; set => this._azureAdRegistered = value; }

        /// <summary>Backing field for <see cref="ChassisType" /> property.</summary>
        private string _chassisType;

        /// <summary>chassisType</summary>
        public string ChassisType { get => this._chassisType; set => this._chassisType = value; }

        /// <summary>Backing field for <see cref="ChromeOSDeviceInfo" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgChromeOSDeviceProperty[] _chromeOSDeviceInfo;

        /// <summary>List of properties of the ChromeOS Device.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgChromeOSDeviceProperty[] ChromeOSDeviceInfo { get => this._chromeOSDeviceInfo; set => this._chromeOSDeviceInfo = value; }

        /// <summary>Backing field for <see cref="CloudPcRemoteActionResults" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgCloudPcRemoteActionResult[] _cloudPcRemoteActionResults;

        public Microsoft.Graph.PowerShell.Users.Models.MgCloudPcRemoteActionResult[] CloudPcRemoteActionResults { get => this._cloudPcRemoteActionResults; set => this._cloudPcRemoteActionResults = value; }

        /// <summary>
        /// Backing field for <see cref="ComplianceGracePeriodExpirationDateTime" /> property.
        /// </summary>
        private global::System.DateTime? _complianceGracePeriodExpirationDateTime;

        /// <summary>
        /// The DateTime when device compliance grace period expires. This property is read-only.
        /// </summary>
        public global::System.DateTime? ComplianceGracePeriodExpirationDateTime { get => this._complianceGracePeriodExpirationDateTime; set => this._complianceGracePeriodExpirationDateTime = value; }

        /// <summary>Backing field for <see cref="ComplianceState" /> property.</summary>
        private string _complianceState;

        /// <summary>complianceState</summary>
        public string ComplianceState { get => this._complianceState; set => this._complianceState = value; }

        /// <summary>
        /// Backing field for <see cref="ConfigurationManagerClientEnabledFeatures" /> property.
        /// </summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgConfigurationManagerClientEnabledFeatures _configurationManagerClientEnabledFeatures;

        /// <summary>configuration Manager client enabled features</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgConfigurationManagerClientEnabledFeatures ConfigurationManagerClientEnabledFeatures { get => (this._configurationManagerClientEnabledFeatures = this._configurationManagerClientEnabledFeatures ?? new Microsoft.Graph.PowerShell.Users.Models.MgConfigurationManagerClientEnabledFeatures()); set => this._configurationManagerClientEnabledFeatures = value; }

        /// <summary>
        /// Backing field for <see cref="ConfigurationManagerClientHealthState" /> property.
        /// </summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgConfigurationManagerClientHealthState _configurationManagerClientHealthState;

        /// <summary>Configuration manager client health state</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgConfigurationManagerClientHealthState ConfigurationManagerClientHealthState { get => (this._configurationManagerClientHealthState = this._configurationManagerClientHealthState ?? new Microsoft.Graph.PowerShell.Users.Models.MgConfigurationManagerClientHealthState()); set => this._configurationManagerClientHealthState = value; }

        /// <summary>
        /// Backing field for <see cref="ConfigurationManagerClientInformation" /> property.
        /// </summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgConfigurationManagerClientInformation _configurationManagerClientInformation;

        /// <summary>Configuration Manager client information synced from SCCM</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgConfigurationManagerClientInformation ConfigurationManagerClientInformation { get => (this._configurationManagerClientInformation = this._configurationManagerClientInformation ?? new Microsoft.Graph.PowerShell.Users.Models.MgConfigurationManagerClientInformation()); set => this._configurationManagerClientInformation = value; }

        /// <summary>Backing field for <see cref="DetectedApps" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgDetectedApp[] _detectedApps;

        /// <summary>All applications currently installed on the device</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgDetectedApp[] DetectedApps { get => this._detectedApps; set => this._detectedApps = value; }

        /// <summary>Backing field for <see cref="DeviceActionResults" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgDeviceActionResult[] _deviceActionResults;

        /// <summary>List of ComplexType deviceActionResult objects. This property is read-only.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgDeviceActionResult[] DeviceActionResults { get => this._deviceActionResults; set => this._deviceActionResults = value; }

        /// <summary>Backing field for <see cref="DeviceCategory" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgDeviceCategory _deviceCategory;

        /// <summary>
        /// Device categories provides a way to organize your devices. Using device categories, company administrators can define
        /// their own categories that make sense to their company. These categories can then be applied to a device in the Intune
        /// Azure console or selected by a user during device enrollment. You can filter reports and create dynamic Azure Active Directory
        /// device groups based on device categories.
        /// </summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgDeviceCategory DeviceCategory { get => (this._deviceCategory = this._deviceCategory ?? new Microsoft.Graph.PowerShell.Users.Models.MgDeviceCategory()); set => this._deviceCategory = value; }

        /// <summary>Backing field for <see cref="DeviceCategoryDisplayName" /> property.</summary>
        private string _deviceCategoryDisplayName;

        /// <summary>Device category display name. This property is read-only.</summary>
        public string DeviceCategoryDisplayName { get => this._deviceCategoryDisplayName; set => this._deviceCategoryDisplayName = value; }

        /// <summary>Backing field for <see cref="DeviceCompliancePolicyStates" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgDeviceCompliancePolicyState[] _deviceCompliancePolicyStates;

        /// <summary>Device compliance policy states for this device.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgDeviceCompliancePolicyState[] DeviceCompliancePolicyStates { get => this._deviceCompliancePolicyStates; set => this._deviceCompliancePolicyStates = value; }

        /// <summary>Backing field for <see cref="DeviceConfigurationStates" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgDeviceConfigurationState[] _deviceConfigurationStates;

        /// <summary>Device configuration states for this device.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgDeviceConfigurationState[] DeviceConfigurationStates { get => this._deviceConfigurationStates; set => this._deviceConfigurationStates = value; }

        /// <summary>Backing field for <see cref="DeviceEnrollmentType" /> property.</summary>
        private string _deviceEnrollmentType;

        /// <summary>deviceEnrollmentType</summary>
        public string DeviceEnrollmentType { get => this._deviceEnrollmentType; set => this._deviceEnrollmentType = value; }

        /// <summary>Backing field for <see cref="DeviceHealthAttestationState" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgDeviceHealthAttestationState _deviceHealthAttestationState;

        /// <summary>deviceHealthAttestationState</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgDeviceHealthAttestationState DeviceHealthAttestationState { get => (this._deviceHealthAttestationState = this._deviceHealthAttestationState ?? new Microsoft.Graph.PowerShell.Users.Models.MgDeviceHealthAttestationState()); set => this._deviceHealthAttestationState = value; }

        /// <summary>Backing field for <see cref="DeviceName" /> property.</summary>
        private string _deviceName;

        /// <summary>Name of the device. This property is read-only.</summary>
        public string DeviceName { get => this._deviceName; set => this._deviceName = value; }

        /// <summary>Backing field for <see cref="DeviceRegistrationState" /> property.</summary>
        private string _deviceRegistrationState;

        /// <summary>deviceRegistrationState</summary>
        public string DeviceRegistrationState { get => this._deviceRegistrationState; set => this._deviceRegistrationState = value; }

        /// <summary>Backing field for <see cref="DeviceType" /> property.</summary>
        private string _deviceType;

        /// <summary>deviceType</summary>
        public string DeviceType { get => this._deviceType; set => this._deviceType = value; }

        /// <summary>Backing field for <see cref="EasActivated" /> property.</summary>
        private bool? _easActivated;

        /// <summary>
        /// Whether the device is Exchange ActiveSync activated. This property is read-only.
        /// </summary>
        public bool? EasActivated { get => this._easActivated; set => this._easActivated = value; }

        /// <summary>Backing field for <see cref="EasActivationDateTime" /> property.</summary>
        private global::System.DateTime? _easActivationDateTime;

        /// <summary>
        /// Exchange ActivationSync activation time of the device. This property is read-only.
        /// </summary>
        public global::System.DateTime? EasActivationDateTime { get => this._easActivationDateTime; set => this._easActivationDateTime = value; }

        /// <summary>Backing field for <see cref="EasDeviceId" /> property.</summary>
        private string _easDeviceId;

        /// <summary>Exchange ActiveSync Id of the device. This property is read-only.</summary>
        public string EasDeviceId { get => this._easDeviceId; set => this._easDeviceId = value; }

        /// <summary>Backing field for <see cref="EmailAddress" /> property.</summary>
        private string _emailAddress;

        /// <summary>Email(s) for the user associated with the device. This property is read-only.</summary>
        public string EmailAddress { get => this._emailAddress; set => this._emailAddress = value; }

        /// <summary>Backing field for <see cref="EnrolledDateTime" /> property.</summary>
        private global::System.DateTime? _enrolledDateTime;

        /// <summary>Enrollment time of the device. This property is read-only.</summary>
        public global::System.DateTime? EnrolledDateTime { get => this._enrolledDateTime; set => this._enrolledDateTime = value; }

        /// <summary>Backing field for <see cref="EthernetMacAddress" /> property.</summary>
        private string _ethernetMacAddress;

        /// <summary>Ethernet MAC. This property is read-only.</summary>
        public string EthernetMacAddress { get => this._ethernetMacAddress; set => this._ethernetMacAddress = value; }

        /// <summary>Backing field for <see cref="ExchangeAccessState" /> property.</summary>
        private string _exchangeAccessState;

        /// <summary>deviceManagementExchangeAccessState</summary>
        public string ExchangeAccessState { get => this._exchangeAccessState; set => this._exchangeAccessState = value; }

        /// <summary>Backing field for <see cref="ExchangeAccessStateReason" /> property.</summary>
        private string _exchangeAccessStateReason;

        /// <summary>deviceManagementExchangeAccessStateReason</summary>
        public string ExchangeAccessStateReason { get => this._exchangeAccessStateReason; set => this._exchangeAccessStateReason = value; }

        /// <summary>Backing field for <see cref="ExchangeLastSuccessfulSyncDateTime" /> property.</summary>
        private global::System.DateTime? _exchangeLastSuccessfulSyncDateTime;

        /// <summary>Last time the device contacted Exchange. This property is read-only.</summary>
        public global::System.DateTime? ExchangeLastSuccessfulSyncDateTime { get => this._exchangeLastSuccessfulSyncDateTime; set => this._exchangeLastSuccessfulSyncDateTime = value; }

        /// <summary>Backing field for <see cref="FreeStorageSpaceInBytes" /> property.</summary>
        private long? _freeStorageSpaceInBytes;

        /// <summary>Free Storage in Bytes. This property is read-only.</summary>
        public long? FreeStorageSpaceInBytes { get => this._freeStorageSpaceInBytes; set => this._freeStorageSpaceInBytes = value; }

        /// <summary>Backing field for <see cref="HardwareInformation" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgHardwareInformation _hardwareInformation;

        /// <summary>Hardware information of a given device.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgHardwareInformation HardwareInformation { get => (this._hardwareInformation = this._hardwareInformation ?? new Microsoft.Graph.PowerShell.Users.Models.MgHardwareInformation()); set => this._hardwareInformation = value; }

        /// <summary>Backing field for <see cref="Iccid" /> property.</summary>
        private string _iccid;

        /// <summary>
        /// Integrated Circuit Card Identifier, it is A SIM card's unique identification number. This property is read-only.
        /// </summary>
        public string Iccid { get => this._iccid; set => this._iccid = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="Imei" /> property.</summary>
        private string _imei;

        /// <summary>IMEI. This property is read-only.</summary>
        public string Imei { get => this._imei; set => this._imei = value; }

        /// <summary>Backing field for <see cref="IsEncrypted" /> property.</summary>
        private bool? _isEncrypted;

        /// <summary>Device encryption status. This property is read-only.</summary>
        public bool? IsEncrypted { get => this._isEncrypted; set => this._isEncrypted = value; }

        /// <summary>Backing field for <see cref="IsSupervised" /> property.</summary>
        private bool? _isSupervised;

        /// <summary>Device supervised status. This property is read-only.</summary>
        public bool? IsSupervised { get => this._isSupervised; set => this._isSupervised = value; }

        /// <summary>Backing field for <see cref="JailBroken" /> property.</summary>
        private string _jailBroken;

        /// <summary>whether the device is jail broken or rooted. This property is read-only.</summary>
        public string JailBroken { get => this._jailBroken; set => this._jailBroken = value; }

        /// <summary>Backing field for <see cref="JoinType" /> property.</summary>
        private string _joinType;

        /// <summary>joinType</summary>
        public string JoinType { get => this._joinType; set => this._joinType = value; }

        /// <summary>Backing field for <see cref="LastSyncDateTime" /> property.</summary>
        private global::System.DateTime? _lastSyncDateTime;

        /// <summary>
        /// The date and time that the device last completed a successful sync with Intune. This property is read-only.
        /// </summary>
        public global::System.DateTime? LastSyncDateTime { get => this._lastSyncDateTime; set => this._lastSyncDateTime = value; }

        /// <summary>Backing field for <see cref="LogCollectionRequests" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgDeviceLogCollectionResponse[] _logCollectionRequests;

        /// <summary>List of log collection requests</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgDeviceLogCollectionResponse[] LogCollectionRequests { get => this._logCollectionRequests; set => this._logCollectionRequests = value; }

        /// <summary>Backing field for <see cref="LostModeState" /> property.</summary>
        private string _lostModeState;

        /// <summary>lostModeState</summary>
        public string LostModeState { get => this._lostModeState; set => this._lostModeState = value; }

        /// <summary>
        /// Backing field for <see cref="ManagedDeviceMobileAppConfigurationStates" /> property.
        /// </summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgManagedDeviceMobileAppConfigurationState[] _managedDeviceMobileAppConfigurationStates;

        /// <summary>Managed device mobile app configuration states for this device.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgManagedDeviceMobileAppConfigurationState[] ManagedDeviceMobileAppConfigurationStates { get => this._managedDeviceMobileAppConfigurationStates; set => this._managedDeviceMobileAppConfigurationStates = value; }

        /// <summary>Backing field for <see cref="ManagedDeviceName" /> property.</summary>
        private string _managedDeviceName;

        /// <summary>
        /// Automatically generated name to identify a device. Can be overwritten to a user friendly name.
        /// </summary>
        public string ManagedDeviceName { get => this._managedDeviceName; set => this._managedDeviceName = value; }

        /// <summary>Backing field for <see cref="ManagedDeviceOwnerType" /> property.</summary>
        private string _managedDeviceOwnerType;

        /// <summary>managedDeviceOwnerType</summary>
        public string ManagedDeviceOwnerType { get => this._managedDeviceOwnerType; set => this._managedDeviceOwnerType = value; }

        /// <summary>Backing field for <see cref="ManagementAgent" /> property.</summary>
        private string _managementAgent;

        /// <summary>managementAgentType</summary>
        public string ManagementAgent { get => this._managementAgent; set => this._managementAgent = value; }

        /// <summary>Backing field for <see cref="ManagementCertificateExpirationDate" /> property.</summary>
        private global::System.DateTime? _managementCertificateExpirationDate;

        /// <summary>
        /// Reports device management certificate expiration date. This property is read-only.
        /// </summary>
        public global::System.DateTime? ManagementCertificateExpirationDate { get => this._managementCertificateExpirationDate; set => this._managementCertificateExpirationDate = value; }

        /// <summary>Backing field for <see cref="ManagementFeatures" /> property.</summary>
        private string _managementFeatures;

        /// <summary>managedDeviceManagementFeatures</summary>
        public string ManagementFeatures { get => this._managementFeatures; set => this._managementFeatures = value; }

        /// <summary>Backing field for <see cref="ManagementState" /> property.</summary>
        private string _managementState;

        /// <summary>managementState</summary>
        public string ManagementState { get => this._managementState; set => this._managementState = value; }

        /// <summary>Backing field for <see cref="Manufacturer" /> property.</summary>
        private string _manufacturer;

        /// <summary>Manufacturer of the device. This property is read-only.</summary>
        public string Manufacturer { get => this._manufacturer; set => this._manufacturer = value; }

        /// <summary>Backing field for <see cref="Meid" /> property.</summary>
        private string _meid;

        /// <summary>MEID. This property is read-only.</summary>
        public string Meid { get => this._meid; set => this._meid = value; }

        /// <summary>Backing field for <see cref="Model" /> property.</summary>
        private string _model;

        /// <summary>Model of the device. This property is read-only.</summary>
        public string Model { get => this._model; set => this._model = value; }

        /// <summary>Backing field for <see cref="Notes" /> property.</summary>
        private string _notes;

        /// <summary>Notes on the device created by IT Admin</summary>
        public string Notes { get => this._notes; set => this._notes = value; }

        /// <summary>Backing field for <see cref="OSVersion" /> property.</summary>
        private string _oSVersion;

        /// <summary>Operating system version of the device. This property is read-only.</summary>
        public string OSVersion { get => this._oSVersion; set => this._oSVersion = value; }

        /// <summary>Backing field for <see cref="OperatingSystem" /> property.</summary>
        private string _operatingSystem;

        /// <summary>Operating system of the device. Windows, iOS, etc. This property is read-only.</summary>
        public string OperatingSystem { get => this._operatingSystem; set => this._operatingSystem = value; }

        /// <summary>Backing field for <see cref="OwnerType" /> property.</summary>
        private string _ownerType;

        /// <summary>ownerType</summary>
        public string OwnerType { get => this._ownerType; set => this._ownerType = value; }

        /// <summary>Backing field for <see cref="PartnerReportedThreatState" /> property.</summary>
        private string _partnerReportedThreatState;

        /// <summary>managedDevicePartnerReportedHealthState</summary>
        public string PartnerReportedThreatState { get => this._partnerReportedThreatState; set => this._partnerReportedThreatState = value; }

        /// <summary>Backing field for <see cref="PhoneNumber" /> property.</summary>
        private string _phoneNumber;

        /// <summary>Phone number of the device. This property is read-only.</summary>
        public string PhoneNumber { get => this._phoneNumber; set => this._phoneNumber = value; }

        /// <summary>Backing field for <see cref="PhysicalMemoryInBytes" /> property.</summary>
        private long? _physicalMemoryInBytes;

        /// <summary>Total Memory in Bytes. This property is read-only.</summary>
        public long? PhysicalMemoryInBytes { get => this._physicalMemoryInBytes; set => this._physicalMemoryInBytes = value; }

        /// <summary>
        /// Backing field for <see cref="PreferMdmOverGroupPolicyAppliedDateTime" /> property.
        /// </summary>
        private global::System.DateTime? _preferMdmOverGroupPolicyAppliedDateTime;

        /// <summary>
        /// Reports the DateTime the preferMdmOverGroupPolicy setting was set. When set, the Intune MDM settings will override Group
        /// Policy settings if there is a conflict. Read Only. This property is read-only.
        /// </summary>
        public global::System.DateTime? PreferMdmOverGroupPolicyAppliedDateTime { get => this._preferMdmOverGroupPolicyAppliedDateTime; set => this._preferMdmOverGroupPolicyAppliedDateTime = value; }

        /// <summary>Backing field for <see cref="ProcessorArchitecture" /> property.</summary>
        private string _processorArchitecture;

        /// <summary>managedDeviceArchitecture</summary>
        public string ProcessorArchitecture { get => this._processorArchitecture; set => this._processorArchitecture = value; }

        /// <summary>Backing field for <see cref="RemoteAssistanceSessionErrorDetails" /> property.</summary>
        private string _remoteAssistanceSessionErrorDetails;

        /// <summary>
        /// An error string that identifies issues when creating Remote Assistance session objects. This property is read-only.
        /// </summary>
        public string RemoteAssistanceSessionErrorDetails { get => this._remoteAssistanceSessionErrorDetails; set => this._remoteAssistanceSessionErrorDetails = value; }

        /// <summary>Backing field for <see cref="RemoteAssistanceSessionUrl" /> property.</summary>
        private string _remoteAssistanceSessionUrl;

        /// <summary>
        /// Url that allows a Remote Assistance session to be established with the device. This property is read-only.
        /// </summary>
        public string RemoteAssistanceSessionUrl { get => this._remoteAssistanceSessionUrl; set => this._remoteAssistanceSessionUrl = value; }

        /// <summary>Backing field for <see cref="RequireUserEnrollmentApproval" /> property.</summary>
        private bool? _requireUserEnrollmentApproval;

        /// <summary>
        /// Reports if the managed iOS device is user approval enrollment. This property is read-only.
        /// </summary>
        public bool? RequireUserEnrollmentApproval { get => this._requireUserEnrollmentApproval; set => this._requireUserEnrollmentApproval = value; }

        /// <summary>Backing field for <see cref="RetireAfterDateTime" /> property.</summary>
        private global::System.DateTime? _retireAfterDateTime;

        /// <summary>
        /// Indicates the time after when a device will be auto retired because of scheduled action. This property is read-only.
        /// </summary>
        public global::System.DateTime? RetireAfterDateTime { get => this._retireAfterDateTime; set => this._retireAfterDateTime = value; }

        /// <summary>Backing field for <see cref="RoleScopeTagIds" /> property.</summary>
        private string[] _roleScopeTagIds;

        /// <summary>List of Scope Tag IDs for this Device instance.</summary>
        public string[] RoleScopeTagIds { get => this._roleScopeTagIds; set => this._roleScopeTagIds = value; }

        /// <summary>Backing field for <see cref="SecurityBaselineStates" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgSecurityBaselineState[] _securityBaselineStates;

        /// <summary>Security baseline states for this device.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgSecurityBaselineState[] SecurityBaselineStates { get => this._securityBaselineStates; set => this._securityBaselineStates = value; }

        /// <summary>Backing field for <see cref="SerialNumber" /> property.</summary>
        private string _serialNumber;

        /// <summary>SerialNumber. This property is read-only.</summary>
        public string SerialNumber { get => this._serialNumber; set => this._serialNumber = value; }

        /// <summary>Backing field for <see cref="SkuFamily" /> property.</summary>
        private string _skuFamily;

        /// <summary>Device sku family</summary>
        public string SkuFamily { get => this._skuFamily; set => this._skuFamily = value; }

        /// <summary>Backing field for <see cref="SkuNumber" /> property.</summary>
        private int? _skuNumber;

        /// <summary>
        /// Device sku number, see also: https://docs.microsoft.com/windows/win32/api/sysinfoapi/nf-sysinfoapi-getproductinfo. Valid
        /// values 0 to 2147483647. This property is read-only.
        /// </summary>
        public int? SkuNumber { get => this._skuNumber; set => this._skuNumber = value; }

        /// <summary>Backing field for <see cref="SpecificationVersion" /> property.</summary>
        private string _specificationVersion;

        /// <summary>Specification version. This property is read-only.</summary>
        public string SpecificationVersion { get => this._specificationVersion; set => this._specificationVersion = value; }

        /// <summary>Backing field for <see cref="SubscriberCarrier" /> property.</summary>
        private string _subscriberCarrier;

        /// <summary>Subscriber Carrier. This property is read-only.</summary>
        public string SubscriberCarrier { get => this._subscriberCarrier; set => this._subscriberCarrier = value; }

        /// <summary>Backing field for <see cref="TotalStorageSpaceInBytes" /> property.</summary>
        private long? _totalStorageSpaceInBytes;

        /// <summary>Total Storage in Bytes. This property is read-only.</summary>
        public long? TotalStorageSpaceInBytes { get => this._totalStorageSpaceInBytes; set => this._totalStorageSpaceInBytes = value; }

        /// <summary>Backing field for <see cref="Udid" /> property.</summary>
        private string _udid;

        /// <summary>Unique Device Identifier for iOS and macOS devices. This property is read-only.</summary>
        public string Udid { get => this._udid; set => this._udid = value; }

        /// <summary>Backing field for <see cref="UserDisplayName" /> property.</summary>
        private string _userDisplayName;

        /// <summary>User display name. This property is read-only.</summary>
        public string UserDisplayName { get => this._userDisplayName; set => this._userDisplayName = value; }

        /// <summary>Backing field for <see cref="UserId" /> property.</summary>
        private string _userId;

        /// <summary>
        /// Unique Identifier for the user associated with the device. This property is read-only.
        /// </summary>
        public string UserId { get => this._userId; set => this._userId = value; }

        /// <summary>Backing field for <see cref="UserPrincipalName" /> property.</summary>
        private string _userPrincipalName;

        /// <summary>Device user principal name. This property is read-only.</summary>
        public string UserPrincipalName { get => this._userPrincipalName; set => this._userPrincipalName = value; }

        /// <summary>Backing field for <see cref="Users" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgUser[] _users;

        /// <summary>The primary users associated with the managed device.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgUser[] Users { get => this._users; set => this._users = value; }

        /// <summary>Backing field for <see cref="UsersLoggedOn" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgLoggedOnUser[] _usersLoggedOn;

        /// <summary>Indicates the last logged on users of a device. This property is read-only.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgLoggedOnUser[] UsersLoggedOn { get => this._usersLoggedOn; set => this._usersLoggedOn = value; }

        /// <summary>Backing field for <see cref="WiFiMacAddress" /> property.</summary>
        private string _wiFiMacAddress;

        /// <summary>Wi-Fi MAC. This property is read-only.</summary>
        public string WiFiMacAddress { get => this._wiFiMacAddress; set => this._wiFiMacAddress = value; }

        /// <summary>Backing field for <see cref="WindowsActiveMalwareCount" /> property.</summary>
        private int? _windowsActiveMalwareCount;

        /// <summary>Count of active malware for this windows device. This property is read-only.</summary>
        public int? WindowsActiveMalwareCount { get => this._windowsActiveMalwareCount; set => this._windowsActiveMalwareCount = value; }

        /// <summary>Backing field for <see cref="WindowsProtectionState" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgWindowsProtectionState _windowsProtectionState;

        /// <summary>Device protection status entity.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgWindowsProtectionState WindowsProtectionState { get => (this._windowsProtectionState = this._windowsProtectionState ?? new Microsoft.Graph.PowerShell.Users.Models.MgWindowsProtectionState()); set => this._windowsProtectionState = value; }

        /// <summary>Backing field for <see cref="WindowsRemediatedMalwareCount" /> property.</summary>
        private int? _windowsRemediatedMalwareCount;

        /// <summary>
        /// Count of remediated malware for this windows device. This property is read-only.
        /// </summary>
        public int? WindowsRemediatedMalwareCount { get => this._windowsRemediatedMalwareCount; set => this._windowsRemediatedMalwareCount = value; }

    }
}