// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>onenoteEntityBaseModel</summary>
    public partial class MgOnenoteEntityBaseModel
    {

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="Self" /> property.</summary>
        private string _self;

        /// <summary>The endpoint where you can get details about the page. Read-only.</summary>
        public string Self { get => this._self; set => this._self = value; }

    }
}