// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>onenoteOperation</summary>
    public partial class MgOnenoteOperation
    {

        /// <summary>The start time of the operation.</summary>
        public global::System.DateTime? CreatedDateTime { get; set; }

        /// <summary>Backing field for <see cref="Error" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgOnenoteOperationError _error;

        /// <summary>onenoteOperationError</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgOnenoteOperationError Error { get => (this._error = this._error ?? new Microsoft.Graph.PowerShell.Users.Models.MgOnenoteOperationError()); set => this._error = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>The time of the last action of the operation.</summary>
        public global::System.DateTime? LastActionDateTime { get; set; }

        /// <summary>Backing field for <see cref="PercentComplete" /> property.</summary>
        private string _percentComplete;

        /// <summary>The operation percent complete if the operation is still in running status.</summary>
        public string PercentComplete { get => this._percentComplete; set => this._percentComplete = value; }

        /// <summary>Backing field for <see cref="ResourceId" /> property.</summary>
        private string _resourceId;

        /// <summary>The resource id.</summary>
        public string ResourceId { get => this._resourceId; set => this._resourceId = value; }

        /// <summary>Backing field for <see cref="ResourceLocation" /> property.</summary>
        private string _resourceLocation;

        /// <summary>
        /// The resource URI for the object. For example, the resource URI for a copied page or section.
        /// </summary>
        public string ResourceLocation { get => this._resourceLocation; set => this._resourceLocation = value; }

        /// <summary>operationStatus</summary>
        public string Status { get; set; }

    }
}