// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>outlookUser</summary>
    public partial class MgOutlookUser
    {

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="MasterCategories" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgOutlookCategory[] _masterCategories;

        /// <summary>A list of categories defined for the user.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgOutlookCategory[] MasterCategories { get => this._masterCategories; set => this._masterCategories = value; }

        /// <summary>Backing field for <see cref="TaskFolders" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgOutlookTaskFolder[] _taskFolders;

        public Microsoft.Graph.PowerShell.Users.Models.MgOutlookTaskFolder[] TaskFolders { get => this._taskFolders; set => this._taskFolders = value; }

        /// <summary>Backing field for <see cref="TaskGroups" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgOutlookTaskGroup[] _taskGroups;

        public Microsoft.Graph.PowerShell.Users.Models.MgOutlookTaskGroup[] TaskGroups { get => this._taskGroups; set => this._taskGroups = value; }

        /// <summary>Backing field for <see cref="Tasks" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgOutlookTask[] _tasks;

        public Microsoft.Graph.PowerShell.Users.Models.MgOutlookTask[] Tasks { get => this._tasks; set => this._tasks = value; }

    }
}