// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>personAward</summary>
    public partial class MgPersonAward
    {

        /// <summary>allowedAudiences</summary>
        public string AllowedAudiences { get; set; }

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet CreatedBy { get; set; }

        /// <summary>Provides the dateTimeOffset for when the entity was created.</summary>
        public global::System.DateTime? CreatedDateTime { get; set; }

        /// <summary>Backing field for <see cref="Description" /> property.</summary>
        private string _description;

        /// <summary>Descpription of the award or honor.</summary>
        public string Description { get => this._description; set => this._description = value; }

        /// <summary>Backing field for <see cref="DisplayName" /> property.</summary>
        private string _displayName;

        /// <summary>Name of the award or honor.</summary>
        public string DisplayName { get => this._displayName; set => this._displayName = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>inferenceData</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgInferenceData Inference { get; set; }

        public bool? IsSearchable { get; set; }

        /// <summary>Backing field for <see cref="IssuedDate" /> property.</summary>
        private global::System.DateTime? _issuedDate;

        /// <summary>The date that the award or honor was granted.</summary>
        public global::System.DateTime? IssuedDate { get => this._issuedDate; set => this._issuedDate = value; }

        /// <summary>Backing field for <see cref="IssuingAuthority" /> property.</summary>
        private string _issuingAuthority;

        /// <summary>Authority which granted the award or honor.</summary>
        public string IssuingAuthority { get => this._issuingAuthority; set => this._issuingAuthority = value; }

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet LastModifiedBy { get; set; }

        /// <summary>Provides the dateTimeOffset for when the entity was created.</summary>
        public global::System.DateTime? LastModifiedDateTime { get; set; }

        /// <summary>personDataSources</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgPersonDataSources Source { get; set; }

        /// <summary>Backing field for <see cref="ThumbnailUrl" /> property.</summary>
        private string _thumbnailUrl;

        /// <summary>URL referencing a thumbnail of the award or honor.</summary>
        public string ThumbnailUrl { get => this._thumbnailUrl; set => this._thumbnailUrl = value; }

        /// <summary>Backing field for <see cref="WebUrl" /> property.</summary>
        private string _webUrl;

        /// <summary>URL referencing the award or honor.</summary>
        public string WebUrl { get => this._webUrl; set => this._webUrl = value; }

    }
}