// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>plannerAssignedToTaskBoardTaskFormat</summary>
    public partial class MgPlannerAssignedToTaskBoardTaskFormat
    {

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="OrderHintsByAssignee" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgPlannerOrderHintsByAssignee _orderHintsByAssignee;

        /// <summary>plannerOrderHintsByAssignee</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgPlannerOrderHintsByAssignee OrderHintsByAssignee { get => (this._orderHintsByAssignee = this._orderHintsByAssignee ?? new Microsoft.Graph.PowerShell.Users.Models.MgPlannerOrderHintsByAssignee()); set => this._orderHintsByAssignee = value; }

        /// <summary>Backing field for <see cref="UnassignedOrderHint" /> property.</summary>
        private string _unassignedOrderHint;

        /// <summary>
        /// Hint value used to order the task on the AssignedTo view of the Task Board when the task is not assigned to anyone, or
        /// if the orderHintsByAssignee dictionary does not provide an order hint for the user the task is assigned to. The format
        /// is defined as outlined here.
        /// </summary>
        public string UnassignedOrderHint { get => this._unassignedOrderHint; set => this._unassignedOrderHint = value; }

    }
}