// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>plannerBucket</summary>
    public partial class MgPlannerBucket
    {

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="Name" /> property.</summary>
        private string _name;

        /// <summary>Name of the bucket.</summary>
        public string Name { get => this._name; set => this._name = value; }

        /// <summary>Backing field for <see cref="OrderHint" /> property.</summary>
        private string _orderHint;

        /// <summary>
        /// Hint used to order items of this type in a list view. The format is defined as outlined here.
        /// </summary>
        public string OrderHint { get => this._orderHint; set => this._orderHint = value; }

        /// <summary>Backing field for <see cref="PlanId" /> property.</summary>
        private string _planId;

        /// <summary>Plan ID to which the bucket belongs.</summary>
        public string PlanId { get => this._planId; set => this._planId = value; }

        /// <summary>Backing field for <see cref="Tasks" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgPlannerTask[] _tasks;

        /// <summary>Read-only. Nullable. The collection of tasks in the bucket.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgPlannerTask[] Tasks { get => this._tasks; set => this._tasks = value; }

    }
}