// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>plannerPlanContainer</summary>
    public partial class MgPlannerPlanContainer
    {

        /// <summary>Backing field for <see cref="ContainerId" /> property.</summary>
        private string _containerId;

        /// <summary>The identifier of the resource that contains the plan.</summary>
        public string ContainerId { get => this._containerId; set => this._containerId = value; }

        /// <summary>Backing field for <see cref="Type" /> property.</summary>
        private string _type;

        /// <summary>plannerContainerType</summary>
        public string Type { get => this._type; set => this._type = value; }

        /// <summary>Backing field for <see cref="Url" /> property.</summary>
        private string _url;

        /// <summary>The full canonical URL of the container.</summary>
        public string Url { get => this._url; set => this._url = value; }

    }
}