// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>scopedRoleMembership</summary>
    public partial class MgScopedRoleMembership
    {

        /// <summary>Backing field for <see cref="AdministrativeUnitId" /> property.</summary>
        private string _administrativeUnitId;

        /// <summary>
        /// Unique identifier for the administrative unit that the directory role is scoped to
        /// </summary>
        public string AdministrativeUnitId { get => this._administrativeUnitId; set => this._administrativeUnitId = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="RoleId" /> property.</summary>
        private string _roleId;

        /// <summary>Unique identifier for the directory role that the member is in.</summary>
        public string RoleId { get => this._roleId; set => this._roleId = value; }

        /// <summary>Backing field for <see cref="RoleMemberInfo" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgIdentity _roleMemberInfo;

        /// <summary>identity</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentity RoleMemberInfo { get => (this._roleMemberInfo = this._roleMemberInfo ?? new Microsoft.Graph.PowerShell.Users.Models.MgIdentity()); set => this._roleMemberInfo = value; }

    }
}