// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>scheduleChangeRequest</summary>
    public partial class MgScheduleChangeRequest
    {

        /// <summary>Backing field for <see cref="AssignedTo" /> property.</summary>
        private string _assignedTo;

        /// <summary>scheduleChangeRequestActor</summary>
        public string AssignedTo { get => this._assignedTo; set => this._assignedTo = value; }

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet CreatedBy { get; set; }

        /// <summary>
        /// The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example,
        /// midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
        /// </summary>
        public global::System.DateTime? CreatedDateTime { get; set; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>identitySet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgIdentitySet LastModifiedBy { get; set; }

        /// <summary>
        /// The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example,
        /// midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z
        /// </summary>
        public global::System.DateTime? LastModifiedDateTime { get; set; }

        /// <summary>Backing field for <see cref="ManagerActionDateTime" /> property.</summary>
        private global::System.DateTime? _managerActionDateTime;

        public global::System.DateTime? ManagerActionDateTime { get => this._managerActionDateTime; set => this._managerActionDateTime = value; }

        /// <summary>Backing field for <see cref="ManagerActionMessage" /> property.</summary>
        private string _managerActionMessage;

        public string ManagerActionMessage { get => this._managerActionMessage; set => this._managerActionMessage = value; }

        /// <summary>Backing field for <see cref="ManagerUserId" /> property.</summary>
        private string _managerUserId;

        public string ManagerUserId { get => this._managerUserId; set => this._managerUserId = value; }

        /// <summary>Backing field for <see cref="SenderDateTime" /> property.</summary>
        private global::System.DateTime? _senderDateTime;

        public global::System.DateTime? SenderDateTime { get => this._senderDateTime; set => this._senderDateTime = value; }

        /// <summary>Backing field for <see cref="SenderMessage" /> property.</summary>
        private string _senderMessage;

        public string SenderMessage { get => this._senderMessage; set => this._senderMessage = value; }

        /// <summary>Backing field for <see cref="SenderUserId" /> property.</summary>
        private string _senderUserId;

        public string SenderUserId { get => this._senderUserId; set => this._senderUserId = value; }

        /// <summary>Backing field for <see cref="State" /> property.</summary>
        private string _state;

        /// <summary>scheduleChangeState</summary>
        public string State { get => this._state; set => this._state = value; }

    }
}