// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>settingSource</summary>
    public partial class MgSettingSource
    {

        /// <summary>Backing field for <see cref="DisplayName" /> property.</summary>
        private string _displayName;

        /// <summary>Not yet documented</summary>
        public string DisplayName { get => this._displayName; set => this._displayName = value; }

        /// <summary>Backing field for <see cref="Id" /> property.</summary>
        private string _id;

        /// <summary>Not yet documented</summary>
        public string Id { get => this._id; set => this._id = value; }

        /// <summary>Backing field for <see cref="SourceType" /> property.</summary>
        private string _sourceType;

        /// <summary>settingSourceType</summary>
        public string SourceType { get => this._sourceType; set => this._sourceType = value; }

    }
}