// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>shiftItem</summary>
    public partial class MgShiftItem
    {

        /// <summary>Backing field for <see cref="Activities" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgShiftActivity[] _activities;

        /// <summary>
        /// An incremental part of a shift which can cover details of when and where an employee is during their shift. For example,
        /// an assignment or a scheduled break or lunch. Required.
        /// </summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgShiftActivity[] Activities { get => this._activities; set => this._activities = value; }

        /// <summary>Backing field for <see cref="DisplayName" /> property.</summary>
        private string _displayName;

        /// <summary>The shift label of the shiftItem.</summary>
        public string DisplayName { get => this._displayName; set => this._displayName = value; }

        public global::System.DateTime? EndDateTime { get; set; }

        /// <summary>Backing field for <see cref="Notes" /> property.</summary>
        private string _notes;

        /// <summary>The shift notes for the shiftItem.</summary>
        public string Notes { get => this._notes; set => this._notes = value; }

        public global::System.DateTime? StartDateTime { get; set; }

        /// <summary>scheduleEntityTheme</summary>
        public string Theme { get; set; }

    }
}