// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>sharepointIds</summary>
    public partial class MgSharepointIds
    {

        /// <summary>Backing field for <see cref="ListId" /> property.</summary>
        private string _listId;

        /// <summary>The unique identifier (guid) for the item's list in SharePoint.</summary>
        public string ListId { get => this._listId; set => this._listId = value; }

        /// <summary>Backing field for <see cref="ListItemId" /> property.</summary>
        private string _listItemId;

        /// <summary>An integer identifier for the item within the containing list.</summary>
        public string ListItemId { get => this._listItemId; set => this._listItemId = value; }

        /// <summary>Backing field for <see cref="ListItemUniqueId" /> property.</summary>
        private string _listItemUniqueId;

        /// <summary>
        /// The unique identifier (guid) for the item within OneDrive for Business or a SharePoint site.
        /// </summary>
        public string ListItemUniqueId { get => this._listItemUniqueId; set => this._listItemUniqueId = value; }

        /// <summary>Backing field for <see cref="SiteId" /> property.</summary>
        private string _siteId;

        /// <summary>The unique identifier (guid) for the item's site collection (SPSite).</summary>
        public string SiteId { get => this._siteId; set => this._siteId = value; }

        /// <summary>Backing field for <see cref="SiteUrl" /> property.</summary>
        private string _siteUrl;

        /// <summary>The SharePoint URL for the site that contains the item.</summary>
        public string SiteUrl { get => this._siteUrl; set => this._siteUrl = value; }

        /// <summary>Backing field for <see cref="TenantId" /> property.</summary>
        private string _tenantId;

        /// <summary>The unique identifier (guid) for the tenancy.</summary>
        public string TenantId { get => this._tenantId; set => this._tenantId = value; }

        /// <summary>Backing field for <see cref="WebId" /> property.</summary>
        private string _webId;

        /// <summary>The unique identifier (guid) for the item's site (SPWeb).</summary>
        public string WebId { get => this._webId; set => this._webId = value; }

    }
}