// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>sizeRange</summary>
    public partial class MgSizeRange
    {

        /// <summary>Backing field for <see cref="MaximumSize" /> property.</summary>
        private int? _maximumSize;

        /// <summary>
        /// The maximum size (in kilobytes) that an incoming message must have in order for a condition or exception to apply.
        /// </summary>
        public int? MaximumSize { get => this._maximumSize; set => this._maximumSize = value; }

        /// <summary>Backing field for <see cref="MinimumSize" /> property.</summary>
        private int? _minimumSize;

        /// <summary>
        /// The minimum size (in kilobytes) that an incoming message must have in order for a condition or exception to apply.
        /// </summary>
        public int? MinimumSize { get => this._minimumSize; set => this._minimumSize = value; }

    }
}