// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>storagePlanInformation</summary>
    public partial class MgStoragePlanInformation
    {

        /// <summary>Backing field for <see cref="UpgradeAvailable" /> property.</summary>
        private bool? _upgradeAvailable;

        /// <summary>Indicates if there are higher storage quota plans available. Read-only.</summary>
        public bool? UpgradeAvailable { get => this._upgradeAvailable; set => this._upgradeAvailable = value; }

    }
}