// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>teamsAppIcon</summary>
    public partial class MgTeamsAppIcon
    {

        /// <summary>Backing field for <see cref="HostedContent" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgTeamworkHostedContent _hostedContent;

        /// <summary>teamworkHostedContent</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgTeamworkHostedContent HostedContent { get => (this._hostedContent = this._hostedContent ?? new Microsoft.Graph.PowerShell.Users.Models.MgTeamworkHostedContent()); set => this._hostedContent = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="WebUrl" /> property.</summary>
        private string _webUrl;

        /// <summary>The web URL that can be used for downloading the image.</summary>
        public string WebUrl { get => this._webUrl; set => this._webUrl = value; }

    }
}