// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>group</summary>
    public partial class MgTermStoreGroup
    {

        /// <summary>Backing field for <see cref="CreatedDateTime" /> property.</summary>
        private global::System.DateTime? _createdDateTime;

        /// <summary>Date and time of group creation. Read-only.</summary>
        public global::System.DateTime? CreatedDateTime { get => this._createdDateTime; set => this._createdDateTime = value; }

        /// <summary>Backing field for <see cref="Description" /> property.</summary>
        private string _description;

        /// <summary>Description giving details on the term usage.</summary>
        public string Description { get => this._description; set => this._description = value; }

        /// <summary>Backing field for <see cref="DisplayName" /> property.</summary>
        private string _displayName;

        /// <summary>Name of group.</summary>
        public string DisplayName { get => this._displayName; set => this._displayName = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="ParentSiteId" /> property.</summary>
        private string _parentSiteId;

        /// <summary>Id of the parent site of this group.</summary>
        public string ParentSiteId { get => this._parentSiteId; set => this._parentSiteId = value; }

        /// <summary>Backing field for <see cref="Scope" /> property.</summary>
        private string _scope;

        /// <summary>termGroupScope</summary>
        public string Scope { get => this._scope; set => this._scope = value; }

        /// <summary>Backing field for <see cref="Sets" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgTermStoreSet[] _sets;

        /// <summary>All sets under the group in a term [store].</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgTermStoreSet[] Sets { get => this._sets; set => this._sets = value; }

    }
}