// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>teamworkTag</summary>
    public partial class MgTeamworkTag
    {

        /// <summary>Backing field for <see cref="Description" /> property.</summary>
        private string _description;

        /// <summary>Tag description as it will appear to the user in Microsoft Teams.</summary>
        public string Description { get => this._description; set => this._description = value; }

        /// <summary>Backing field for <see cref="DisplayName" /> property.</summary>
        private string _displayName;

        /// <summary>Tag name as it will appear to the user in Microsoft Teams.</summary>
        public string DisplayName { get => this._displayName; set => this._displayName = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="MemberCount" /> property.</summary>
        private int? _memberCount;

        /// <summary>The number of users assigned to the tag.</summary>
        public int? MemberCount { get => this._memberCount; set => this._memberCount = value; }

        /// <summary>Backing field for <see cref="Members" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgTeamworkTagMember[] _members;

        /// <summary>Users assigned to the tag.</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgTeamworkTagMember[] Members { get => this._members; set => this._members = value; }

        /// <summary>Backing field for <see cref="TagType" /> property.</summary>
        private string _tagType;

        /// <summary>teamworkTagType</summary>
        public string TagType { get => this._tagType; set => this._tagType = value; }

        /// <summary>Backing field for <see cref="TeamId" /> property.</summary>
        private string _teamId;

        /// <summary>ID of the team in which the tag is defined.</summary>
        public string TeamId { get => this._teamId; set => this._teamId = value; }

    }
}