// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>teamMessagingSettings</summary>
    public partial class MgTeamMessagingSettings
    {

        /// <summary>Backing field for <see cref="AllowChannelMentions" /> property.</summary>
        private bool? _allowChannelMentions;

        /// <summary>If set to true, @channel mentions are allowed.</summary>
        public bool? AllowChannelMentions { get => this._allowChannelMentions; set => this._allowChannelMentions = value; }

        /// <summary>Backing field for <see cref="AllowOwnerDeleteMessages" /> property.</summary>
        private bool? _allowOwnerDeleteMessages;

        /// <summary>If set to true, owners can delete any message.</summary>
        public bool? AllowOwnerDeleteMessages { get => this._allowOwnerDeleteMessages; set => this._allowOwnerDeleteMessages = value; }

        /// <summary>Backing field for <see cref="AllowTeamMentions" /> property.</summary>
        private bool? _allowTeamMentions;

        /// <summary>If set to true, @team mentions are allowed.</summary>
        public bool? AllowTeamMentions { get => this._allowTeamMentions; set => this._allowTeamMentions = value; }

        /// <summary>Backing field for <see cref="AllowUserDeleteMessages" /> property.</summary>
        private bool? _allowUserDeleteMessages;

        /// <summary>If set to true, users can delete their messages.</summary>
        public bool? AllowUserDeleteMessages { get => this._allowUserDeleteMessages; set => this._allowUserDeleteMessages = value; }

        /// <summary>Backing field for <see cref="AllowUserEditMessages" /> property.</summary>
        private bool? _allowUserEditMessages;

        /// <summary>If set to true, users can edit their messages.</summary>
        public bool? AllowUserEditMessages { get => this._allowUserEditMessages; set => this._allowUserEditMessages = value; }

    }
}