// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>thumbnail</summary>
    public partial class MgThumbnail
    {

        /// <summary>Backing field for <see cref="Content" /> property.</summary>
        private byte[] _content;

        /// <summary>The content stream for the thumbnail.</summary>
        public byte[] Content { get => this._content; set => this._content = value; }

        /// <summary>Backing field for <see cref="Height" /> property.</summary>
        private int? _height;

        /// <summary>The height of the thumbnail, in pixels.</summary>
        public int? Height { get => this._height; set => this._height = value; }

        /// <summary>Backing field for <see cref="SourceItemId" /> property.</summary>
        private string _sourceItemId;

        /// <summary>
        /// The unique identifier of the item that provided the thumbnail. This is only available when a folder thumbnail is requested.
        /// </summary>
        public string SourceItemId { get => this._sourceItemId; set => this._sourceItemId = value; }

        /// <summary>Backing field for <see cref="Url" /> property.</summary>
        private string _url;

        /// <summary>The URL used to fetch the thumbnail content.</summary>
        public string Url { get => this._url; set => this._url = value; }

        /// <summary>Backing field for <see cref="Width" /> property.</summary>
        private int? _width;

        /// <summary>The width of the thumbnail, in pixels.</summary>
        public int? Width { get => this._width; set => this._width = value; }

    }
}