// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>timeClockSettings</summary>
    public partial class MgTimeClockSettings
    {

        /// <summary>Backing field for <see cref="ApprovedLocation" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgGeoCoordinates _approvedLocation;

        /// <summary>geoCoordinates</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgGeoCoordinates ApprovedLocation { get => (this._approvedLocation = this._approvedLocation ?? new Microsoft.Graph.PowerShell.Users.Models.MgGeoCoordinates()); set => this._approvedLocation = value; }

    }
}