// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>usageRight</summary>
    public partial class MgUsageRight
    {

        /// <summary>Backing field for <see cref="CatalogId" /> property.</summary>
        private string _catalogId;

        /// <summary>Product id corresponding to the usage right.</summary>
        public string CatalogId { get => this._catalogId; set => this._catalogId = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="ServiceIdentifier" /> property.</summary>
        private string _serviceIdentifier;

        /// <summary>Identifier of the service corresponding to the usage right.</summary>
        public string ServiceIdentifier { get => this._serviceIdentifier; set => this._serviceIdentifier = value; }

        /// <summary>Backing field for <see cref="State" /> property.</summary>
        private string _state;

        /// <summary>usageRightState</summary>
        public string State { get => this._state; set => this._state = value; }

    }
}