// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>versionAction</summary>
    public partial class MgVersionAction
    {

        /// <summary>Backing field for <see cref="NewVersion" /> property.</summary>
        private string _newVersion;

        /// <summary>The name of the new version that was created by this action.</summary>
        public string NewVersion { get => this._newVersion; set => this._newVersion = value; }

    }
}