// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>workbookOperationError</summary>
    public partial class MgWorkbookOperationError
    {

        /// <summary>Backing field for <see cref="Code" /> property.</summary>
        private string _code;

        /// <summary>The error code.</summary>
        public string Code { get => this._code; set => this._code = value; }

        /// <summary>Backing field for <see cref="InnerError" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgWorkbookOperationError _innerError;

        /// <summary>workbookOperationError</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgWorkbookOperationError InnerError { get => (this._innerError = this._innerError ?? new Microsoft.Graph.PowerShell.Users.Models.MgWorkbookOperationError()); set => this._innerError = value; }

        /// <summary>Backing field for <see cref="Message" /> property.</summary>
        private string _message;

        /// <summary>The error message.</summary>
        public string Message { get => this._message; set => this._message = value; }

    }
}