// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>workingHours</summary>
    public partial class MgWorkingHours
    {

        /// <summary>Backing field for <see cref="DaysOfWeek" /> property.</summary>
        private string[] _daysOfWeek;

        /// <summary>The days of the week on which the user works.</summary>
        public string[] DaysOfWeek { get => this._daysOfWeek; set => this._daysOfWeek = value; }

        /// <summary>Backing field for <see cref="EndTime" /> property.</summary>
        private string _endTime;

        /// <summary>The time of the day that the user stops working.</summary>
        public string EndTime { get => this._endTime; set => this._endTime = value; }

        /// <summary>Backing field for <see cref="StartTime" /> property.</summary>
        private string _startTime;

        /// <summary>The time of the day that the user starts working.</summary>
        public string StartTime { get => this._startTime; set => this._startTime = value; }

        /// <summary>Backing field for <see cref="TimeZone" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgTimeZoneBase _timeZone;

        /// <summary>timeZoneBase</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgTimeZoneBase TimeZone { get => (this._timeZone = this._timeZone ?? new Microsoft.Graph.PowerShell.Users.Models.MgTimeZoneBase()); set => this._timeZone = value; }

    }
}