// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>workbookSortField</summary>
    public partial class MgWorkbookSortField
    {

        /// <summary>Backing field for <see cref="Ascending" /> property.</summary>
        private bool? _ascending;

        /// <summary>Represents whether the sorting is done in an ascending fashion.</summary>
        public bool? Ascending { get => this._ascending; set => this._ascending = value; }

        /// <summary>Backing field for <see cref="Color" /> property.</summary>
        private string _color;

        /// <summary>
        /// Represents the color that is the target of the condition if the sorting is on font or cell color.
        /// </summary>
        public string Color { get => this._color; set => this._color = value; }

        /// <summary>Backing field for <see cref="DataOption" /> property.</summary>
        private string _dataOption;

        /// <summary>
        /// Represents additional sorting options for this field. Possible values are: Normal, TextAsNumber.
        /// </summary>
        public string DataOption { get => this._dataOption; set => this._dataOption = value; }

        /// <summary>Backing field for <see cref="Icon" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgWorkbookIcon _icon;

        /// <summary>workbookIcon</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgWorkbookIcon Icon { get => (this._icon = this._icon ?? new Microsoft.Graph.PowerShell.Users.Models.MgWorkbookIcon()); set => this._icon = value; }

        /// <summary>Backing field for <see cref="Key" /> property.</summary>
        private int? _key;

        /// <summary>
        /// Represents the column (or row, depending on the sort orientation) that the condition is on. Represented as an offset from
        /// the first column (or row).
        /// </summary>
        public int? Key { get => this._key; set => this._key = value; }

        /// <summary>Backing field for <see cref="SortOn" /> property.</summary>
        private string _sortOn;

        /// <summary>
        /// Represents the type of sorting of this condition. Possible values are: Value, CellColor, FontColor, Icon.
        /// </summary>
        public string SortOn { get => this._sortOn; set => this._sortOn = value; }

    }
}