// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>workbookNamedItem</summary>
    public partial class MgWorkbookNamedItem
    {

        /// <summary>Backing field for <see cref="Comment" /> property.</summary>
        private string _comment;

        /// <summary>Represents the comment associated with this name.</summary>
        public string Comment { get => this._comment; set => this._comment = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="Name" /> property.</summary>
        private string _name;

        /// <summary>The name of the object. Read-only.</summary>
        public string Name { get => this._name; set => this._name = value; }

        /// <summary>Backing field for <see cref="Scope" /> property.</summary>
        private string _scope;

        /// <summary>
        /// Indicates whether the name is scoped to the workbook or to a specific worksheet. Read-only.
        /// </summary>
        public string Scope { get => this._scope; set => this._scope = value; }

        /// <summary>Backing field for <see cref="Type" /> property.</summary>
        private string _type;

        /// <summary>
        /// Indicates what type of reference is associated with the name. Possible values are: String, Integer, Double, Boolean, Range.
        /// Read-only.
        /// </summary>
        public string Type { get => this._type; set => this._type = value; }

        /// <summary>Backing field for <see cref="Value" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgJson _value;

        /// <summary>Json</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgJson Value { get => (this._value = this._value ?? new Microsoft.Graph.PowerShell.Users.Models.MgJson()); set => this._value = value; }

        /// <summary>Backing field for <see cref="Visible" /> property.</summary>
        private bool? _visible;

        /// <summary>Specifies whether the object is visible or not.</summary>
        public bool? Visible { get => this._visible; set => this._visible = value; }

        /// <summary>Backing field for <see cref="Worksheet" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgWorkbookWorksheet _worksheet;

        /// <summary>workbookWorksheet</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgWorkbookWorksheet Worksheet { get => (this._worksheet = this._worksheet ?? new Microsoft.Graph.PowerShell.Users.Models.MgWorkbookWorksheet()); set => this._worksheet = value; }

    }
}