// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>workbookTableRow</summary>
    public partial class MgWorkbookTableRow
    {

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="Index" /> property.</summary>
        private int? _index;

        /// <summary>
        /// Returns the index number of the row within the rows collection of the table. Zero-indexed. Read-only.
        /// </summary>
        public int? Index { get => this._index; set => this._index = value; }

        /// <summary>Backing field for <see cref="Values" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgJson _values;

        /// <summary>Json</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgJson Values { get => (this._values = this._values ?? new Microsoft.Graph.PowerShell.Users.Models.MgJson()); set => this._values = value; }

    }
}