// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>workbookChartDataLabels</summary>
    public partial class MgWorkbookChartDataLabels
    {

        /// <summary>Backing field for <see cref="Format" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartDataLabelFormat _format;

        /// <summary>workbookChartDataLabelFormat</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartDataLabelFormat Format { get => (this._format = this._format ?? new Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartDataLabelFormat()); set => this._format = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="Position" /> property.</summary>
        private string _position;

        /// <summary>
        /// DataLabelPosition value that represents the position of the data label. The possible values are: None, Center, InsideEnd,
        /// InsideBase, OutsideEnd, Left, Right, Top, Bottom, BestFit, Callout.
        /// </summary>
        public string Position { get => this._position; set => this._position = value; }

        /// <summary>Backing field for <see cref="Separator" /> property.</summary>
        private string _separator;

        /// <summary>String representing the separator used for the data labels on a chart.</summary>
        public string Separator { get => this._separator; set => this._separator = value; }

        /// <summary>Backing field for <see cref="ShowBubbleSize" /> property.</summary>
        private bool? _showBubbleSize;

        /// <summary>Boolean value representing if the data label bubble size is visible or not.</summary>
        public bool? ShowBubbleSize { get => this._showBubbleSize; set => this._showBubbleSize = value; }

        /// <summary>Backing field for <see cref="ShowCategoryName" /> property.</summary>
        private bool? _showCategoryName;

        /// <summary>Boolean value representing if the data label category name is visible or not.</summary>
        public bool? ShowCategoryName { get => this._showCategoryName; set => this._showCategoryName = value; }

        /// <summary>Backing field for <see cref="ShowLegendKey" /> property.</summary>
        private bool? _showLegendKey;

        /// <summary>Boolean value representing if the data label legend key is visible or not.</summary>
        public bool? ShowLegendKey { get => this._showLegendKey; set => this._showLegendKey = value; }

        /// <summary>Backing field for <see cref="ShowPercentage" /> property.</summary>
        private bool? _showPercentage;

        /// <summary>Boolean value representing if the data label percentage is visible or not.</summary>
        public bool? ShowPercentage { get => this._showPercentage; set => this._showPercentage = value; }

        /// <summary>Backing field for <see cref="ShowSeriesName" /> property.</summary>
        private bool? _showSeriesName;

        /// <summary>Boolean value representing if the data label series name is visible or not.</summary>
        public bool? ShowSeriesName { get => this._showSeriesName; set => this._showSeriesName = value; }

        /// <summary>Backing field for <see cref="ShowValue" /> property.</summary>
        private bool? _showValue;

        /// <summary>Boolean value representing if the data label value is visible or not.</summary>
        public bool? ShowValue { get => this._showValue; set => this._showValue = value; }

    }
}