// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    /// <summary>workbookChartAxis</summary>
    public partial class MgWorkbookChartAxis
    {

        /// <summary>Backing field for <see cref="Format" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartAxisFormat _format;

        /// <summary>workbookChartAxisFormat</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartAxisFormat Format { get => (this._format = this._format ?? new Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartAxisFormat()); set => this._format = value; }

        /// <summary>Read-only.</summary>
        public string Id { get; set; }

        /// <summary>Backing field for <see cref="MajorGridlines" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartGridlines _majorGridlines;

        /// <summary>workbookChartGridlines</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartGridlines MajorGridlines { get => (this._majorGridlines = this._majorGridlines ?? new Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartGridlines()); set => this._majorGridlines = value; }

        /// <summary>Backing field for <see cref="MajorUnit" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgJson _majorUnit;

        /// <summary>Json</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgJson MajorUnit { get => (this._majorUnit = this._majorUnit ?? new Microsoft.Graph.PowerShell.Users.Models.MgJson()); set => this._majorUnit = value; }

        /// <summary>Backing field for <see cref="Maximum" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgJson _maximum;

        /// <summary>Json</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgJson Maximum { get => (this._maximum = this._maximum ?? new Microsoft.Graph.PowerShell.Users.Models.MgJson()); set => this._maximum = value; }

        /// <summary>Backing field for <see cref="Minimum" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgJson _minimum;

        /// <summary>Json</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgJson Minimum { get => (this._minimum = this._minimum ?? new Microsoft.Graph.PowerShell.Users.Models.MgJson()); set => this._minimum = value; }

        /// <summary>Backing field for <see cref="MinorGridlines" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartGridlines _minorGridlines;

        /// <summary>workbookChartGridlines</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartGridlines MinorGridlines { get => (this._minorGridlines = this._minorGridlines ?? new Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartGridlines()); set => this._minorGridlines = value; }

        /// <summary>Backing field for <see cref="MinorUnit" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgJson _minorUnit;

        /// <summary>Json</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgJson MinorUnit { get => (this._minorUnit = this._minorUnit ?? new Microsoft.Graph.PowerShell.Users.Models.MgJson()); set => this._minorUnit = value; }

        /// <summary>Backing field for <see cref="Title" /> property.</summary>
        private Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartAxisTitle _title;

        /// <summary>workbookChartAxisTitle</summary>
        public Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartAxisTitle Title { get => (this._title = this._title ?? new Microsoft.Graph.PowerShell.Users.Models.MgWorkbookChartAxisTitle()); set => this._title = value; }

    }
}