// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.6.2, generator: @autorest/powershell@3.0.0)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace Microsoft.Graph.PowerShell.Users.Models
{

    public partial class UsersIdentity
    {

        /// <summary>Backing field for <see cref="AttachmentId" /> property.</summary>
        private string _attachmentId;

        /// <summary>key: id of attachment</summary>
        public string AttachmentId { get => this._attachmentId; set => this._attachmentId = value; }

        /// <summary>Backing field for <see cref="ExtensionId" /> property.</summary>
        private string _extensionId;

        /// <summary>key: id of extension</summary>
        public string ExtensionId { get => this._extensionId; set => this._extensionId = value; }

        /// <summary>Backing field for <see cref="LicenseDetailsId" /> property.</summary>
        private string _licenseDetailsId;

        /// <summary>key: id of licenseDetails</summary>
        public string LicenseDetailsId { get => this._licenseDetailsId; set => this._licenseDetailsId = value; }

        /// <summary>Backing field for <see cref="LinkedResourceId" /> property.</summary>
        private string _linkedResourceId;

        /// <summary>key: id of linkedResource</summary>
        public string LinkedResourceId { get => this._linkedResourceId; set => this._linkedResourceId = value; }

        /// <summary>Backing field for <see cref="MultiValueLegacyExtendedPropertyId" /> property.</summary>
        private string _multiValueLegacyExtendedPropertyId;

        /// <summary>key: id of multiValueLegacyExtendedProperty</summary>
        public string MultiValueLegacyExtendedPropertyId { get => this._multiValueLegacyExtendedPropertyId; set => this._multiValueLegacyExtendedPropertyId = value; }

        /// <summary>Backing field for <see cref="NotificationId" /> property.</summary>
        private string _notificationId;

        /// <summary>key: id of notification</summary>
        public string NotificationId { get => this._notificationId; set => this._notificationId = value; }

        /// <summary>Backing field for <see cref="OutlookCategoryId" /> property.</summary>
        private string _outlookCategoryId;

        /// <summary>key: id of outlookCategory</summary>
        public string OutlookCategoryId { get => this._outlookCategoryId; set => this._outlookCategoryId = value; }

        /// <summary>Backing field for <see cref="OutlookTaskFolderId" /> property.</summary>
        private string _outlookTaskFolderId;

        /// <summary>key: id of outlookTaskFolder</summary>
        public string OutlookTaskFolderId { get => this._outlookTaskFolderId; set => this._outlookTaskFolderId = value; }

        /// <summary>Backing field for <see cref="OutlookTaskGroupId" /> property.</summary>
        private string _outlookTaskGroupId;

        /// <summary>key: id of outlookTaskGroup</summary>
        public string OutlookTaskGroupId { get => this._outlookTaskGroupId; set => this._outlookTaskGroupId = value; }

        /// <summary>Backing field for <see cref="OutlookTaskId" /> property.</summary>
        private string _outlookTaskId;

        /// <summary>key: id of outlookTask</summary>
        public string OutlookTaskId { get => this._outlookTaskId; set => this._outlookTaskId = value; }

        /// <summary>Backing field for <see cref="ProfilePhotoId" /> property.</summary>
        private string _profilePhotoId;

        /// <summary>key: id of profilePhoto</summary>
        public string ProfilePhotoId { get => this._profilePhotoId; set => this._profilePhotoId = value; }

        /// <summary>Backing field for <see cref="SingleValueLegacyExtendedPropertyId" /> property.</summary>
        private string _singleValueLegacyExtendedPropertyId;

        /// <summary>key: id of singleValueLegacyExtendedProperty</summary>
        public string SingleValueLegacyExtendedPropertyId { get => this._singleValueLegacyExtendedPropertyId; set => this._singleValueLegacyExtendedPropertyId = value; }

        /// <summary>Backing field for <see cref="TodoTaskId" /> property.</summary>
        private string _todoTaskId;

        /// <summary>key: id of todoTask</summary>
        public string TodoTaskId { get => this._todoTaskId; set => this._todoTaskId = value; }

        /// <summary>Backing field for <see cref="TodoTaskListId" /> property.</summary>
        private string _todoTaskListId;

        /// <summary>key: id of todoTaskList</summary>
        public string TodoTaskListId { get => this._todoTaskListId; set => this._todoTaskListId = value; }

        /// <summary>Backing field for <see cref="UserId" /> property.</summary>
        private string _userId;

        /// <summary>key: id of user</summary>
        public string UserId { get => this._userId; set => this._userId = value; }

    }
}